### ISSUE TITLE
ContractInfo for MULTISIG_TRANSACTION types

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-transaction-service#100]
# What is needed?
We would like to have a `ContractInfo` class as part of the `Transaction` response when the field `Transaction.to` corresponds to a ERC20/ERC721 token or a known contract. For tokens, this would contain decimals, value, symbol, etc. The usual `TokenInfo` where applicable.

# Background
We would like to have for transactions that have not been executed yet, information on what their interaction with the blockchain will be.

# Endpoint
Any transaction related endpoint

# Related Issues
https://github.com/gnosis/safe-transaction-service/issues/96

## Response
We would like to match the structure shown in the #96 
```json
{
    "address": "string" //Solidity.Address,
    "decimals": "integer" , // nullable
    "symbol": "`string", // nullable
    "name": "string", // nullable
    "logoUri": "string", //nullable
    "tokenType": "string", // can be one of the values ERC20, ERC721, UNKNOWN
    "tokenId": "string" //nullable
}
```

`tokenType` can only take values for `ERC20, ERC721, UNKNOWN`. For now the structure is very token specific, only the values that make sense for a certain standard are set and the rest are left `null`.

**Comment by Uxio0** [comment]
Depends on #37

**Comment by rmeissner** [comment]
The data for this field can theoretically be other stuff than tokens (e.g. a uniswap contract). I would like of this would be covered by the proposed data structure.

I would go with something like:
Base:
```json
{
  "type": "string",
  "name: "string",
  "logoUri": "string or null"
}
```

Where `type` string is one of the supported types. E.g. `ERC20` or `ERC721`
I would propose to always have at least have a name if we know this contract so that we can display it to the user. Also have the logoUri always as a nullable string so that even without knowing more about the type in the client we could at least display a name and image (if provided by the backend).

ERC20:
```json
{
  "type": "ERC20", 
  "decimals": "integer" ,
  "symbol": "string",
  "name": "string"
}
```

ERC721:
```json
{
  "type": "ERC721", 
  "name": "string",
  "symbol": "string"
}
```

**Comment by Uxio0** [comment]
I was thinking about this issue, then we would need to have a database of contracts (besides tokens) so I can get the name, what do you think @rmeissner ?

**Comment by rmeissner** [comment]
I thought we start with tokens and add other types later. But yeah I think in the long run we need a contract database or a trusted source for this.

**Comment by Uxio0** [comment]
As discussed with @lukasschor and @rmeissner: 

@jpalvarezl @DmitryBespalov , while I was implementing this issue I realised it could be a big source of problems for both clients and backend:
- Different logics depending on the contract
- Different serializers depending on the contract
- Clients not being able to deserialize a new type of contract, so backend will be always informing and making sure that clients know about the new contracts (other teams will start asking to show custom information if contract is Gnosis Protocol, Uniswap, etc. so it will not just be Safe Team asking for new contracts)
- Making the endpoint slower as we need another more query to get information about the contract, sometimes even from blockchain.
- This is the core endpoint the clients will use

The options I see:
- Closing this ticket as `won't implement` and implement in @jpalvarezl service client gateway in the future. In the meantime you can get information from tokens from `https://safe-transaction.mainnet.gnosis.io/api/v1/tokens/<token-checksum-address>/`. This endpoint is cached and should be really fast.
- Implementing basic information that will be common to multiple contracts, but I see work and perfomance decrease and not a lot to gain here:
```json
{
  "type": "string",
  "name": "string",
}
```

I would go with no implementing this ticket for now
