### ISSUE TITLE
Decode Request / Sablier / Idle / Compound (comptroller) / Aave

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe-transaction-service#114]
# What is this about?
Decode transactions made with Safe Apps in the backend, so we can eventually display the decoded data in our frontends. The contract addresses and ABIs are listed below.

# Request
MAINNET - ERC20 proxy contract: 0x5f821c20947ff9be22e823edc5b3c709b33121b3 - https://github.com/RequestNetwork/requestNetwork/blob/master/packages/smart-contracts/artifacts/ERC20Proxy/0.1.0.json

MAINNET - Ethereum proxy contract: 0x37a8f5f64f2a84f2377481537f04d2a59c9f59b6 - https://github.com/RequestNetwork/requestNetwork/blob/master/packages/smart-contracts/artifacts/EthereumProxy/0.1.0.json

RINKEBY - ERC20 proxy contract: 0x162edb802fae75b9ee4288345735008ba51a4ec9 - https://github.com/RequestNetwork/requestNetwork/blob/master/packages/smart-contracts/artifacts/ERC20Proxy/0.1.0.json (same ABI) (edited) 

RINKEBY- Ethereum proxy contract: 0x9c6c7817e3679c4b3f9ef9486001eae5aaed25ff - https://github.com/RequestNetwork/requestNetwork/blob/master/packages/smart-contracts/artifacts/EthereumProxy/0.1.0.json (same ABI)

# Idle
Contract addresses & ABI: https://developers.idle.finance/contracts-and-codebase

# Sablier
Contract addresses: https://github.com/sablierhq/sablier
ABI: https://github.com/sablierhq/sablier-abis

# Aave
ABI: https://github.com/aave/aave-protocol/tree/master/abi

**Comment by Uxio0** [comment]
@lukasschor Can you add links for the missing ones?

**Comment by Uxio0** [comment]
@lukasschor All that contracts should be supported, can you test it on staging?
