### ISSUE TITLE
BUG: Can't POST execution confirmation with removed owner after removal tx is confirmed

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-transaction-service#12]
### What is needed?

If you execute transaction for `.removeOwner` method with the owner account it is going to remove, the service will return 422 status code when trying to POST execution tx. (I guess `replaceOwner` is affected too)

Since we don't do optimistic updates on the frontend, we send a POST request to the service only when TX is confirmed, because there are too much possible failures: tx failed, user rejected tx, etc, we need some workaround for this.

### Why is it needed?

So the frontend can know if the TX is executed.

### When is it needed?

We need this for v0.1.0 to function properly. I'd say we need this as soon as possible, but let's decide it collectively. 

**Screenshot with the request:**
![export](https://user-images.githubusercontent.com/16622558/61049843-8af36500-a3f6-11e9-8cb5-6c68384c9338.png)

**Comment by Uxio0** [comment]
@mikheevm, I have just deployed a patch, can you confirm if it's now working for you?

**Comment by mikheevm** [comment]
@Uxio0 I've just tried it and it works as expected. Thank you for the fix :)
