### ISSUE TITLE
Missing fields in all-transactions response on mainnet: tokenId and tokenInfo are missing 

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-transaction-service#122]
**Describe the bug**
ERC20_TRANSFERS are missing tokenId and tokenInfo fields. Those are required by the mobile client to show correct data in a transaction list.

**To Reproduce**
https://safe-transaction.gnosis.io/api/v1/safes/0x1D5Fceb726FcbAA3d7D9885b8666305ED44Ad23E/all-transactions/?limit=150

Mainnet

**Comment by rmeissner** [comment]
Erc20 transfers don't have a tokenId, that field is for erc721 transfers

**Comment by rmeissner** [comment]
Also token info is present on staging, so maybe it is not deployed yet?

**Comment by Uxio0** [comment]
It's not deployed yet @elgatovital
