### ISSUE TITLE
Issue with TUSD price oracle

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#125]
**Describe the bug**
API returns wrong USD price for TUSD

**To Reproduce**
https://safe-transaction.gnosis.io/api/v1/safes/<safe_address>/balances/usd/
The Safe has >40k TUSD but the fiat value is <1USD

**Expected behavior**
Correct value, somewhere close to 40k USD

**Additional context**
I'll share the Safe address on Slack. It was sent to me via DM, so didn't want to expose here: https://gnosisinc.slack.com/archives/C63LQTGNB/p1595954225101900

**Comment by tschubotz** [comment]
A related issue was reported by someone during Safe creation. 
![image](https://user-images.githubusercontent.com/1380529/88772866-a6f0b280-d181-11ea-8aac-1e4beb35ce77.png)

**Comment by Uxio0** [comment]
@tschubotz There was an issue with the price oracles. It has been fixed now in every environment (included production)
