### ISSUE TITLE
Use the same transaction response for `/transactions/` endpoint

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#126]
# What is needed?
- To have the same response on `/transactions/<tx-hash>/` (deprecated in favour of  `/multisig-transactions/<tx-hash>/`) than on `all-transactions` endpoint

**Comment by Uxio0** [comment]
Is this really needed with the safe gateway? As I checked, we are returning the same than in `/transactions/` (deprecated in favour of `/multisig-transactions/`). `all-transactions` do a lot of magic and is more slow, if I modify this endpoint it would make sense to modify also `/transactions/`, making the endpoint slower.

My opinion is that if this is not needed anymore I would not modify the endpoints to make them slower, what do you think @DmitryBespalov (I think you were the one asking for this) @jpalvarezl @rmeissner?

**Comment by DmitryBespalov** [comment]
not needed for mobile clients, because we're using client gateway. No idea if needed for the gateway.

**Comment by jpalvarezl** [comment]
We are using for transaction details the `/transactions/<tx-hash>/` endpoint. I will open a ticket for updating that to use the `/multisig-transaction/` endpoint, provided that we can filter by `tx_hash`. That's essentially the only filter we use.

I am not sure what changes are proposed in this issue, though. We are already using the same `DTO` we use for the `/all-transactions/` endpoint with the `/transactions` endpoint which seems to work fine. Maybe I am missing something 🤔

**Comment by Uxio0** [comment]
> We are using for transaction details the `/transactions/<tx-hash>/` endpoint. I will open a ticket for updating that to use the `/multisig-transaction/` endpoint, provided that we can filter by `tx_hash`. That's essentially the only filter we use.
👍 

> I am not sure what changes are proposed in this issue, though. We are already using the same `DTO` we use for the `/all-transactions/` endpoint with the `/transactions` endpoint which seems to work fine. Maybe I am missing something 🤔

Returning also `ERC20/721 transfers`, which are returned on the `all-transactions` endpoint but not on this one, but if it's not needed I wouldn't do that

**Comment by jpalvarezl** [comment]
No need to add more data for the client gateway, transfers are inferred from the `dataDecoded` field presently.

**Comment by jpalvarezl** [comment]
missing token information is also fetched and cached if required
