### ISSUE TITLE
Transaction analytics

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#131]
# Context

We are looking for ways to measure activity of users of the web interface. Specifically, we would like to lean more about the impact of Safe apps. We already have some on-chain insights: https://explore.duneanalytics.com/dashboard/gnosis-safe---safe-apps-transactions However those don't cover things like the tx builder and also off-chain signatures cannot be covered.

# Goal

Answer the following question:

- How many txs have been executed via the web interface per day, ideally, group by type:
  - Pure ETH transfer
  - Pure ERC20 transfer
  - Other contract interaction
  - Safe app transaction (We need to know which app triggered it.)

Once Uxio is back, let's talk about the best way to get this data (E.g. provide Tobi with full database access :P )

**Comment by rmeissner** [comment]
maybe we can use webhooks to collect the data in a separate place (so that we don't have to do the calculations for this in the transaction service)

**Comment by rmeissner** [comment]
This should be timeboxed: if it takes to long we should reprioritize it
