### ISSUE TITLE
Transactions are not correctly ordered by nonce in all-transactions endpoint

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-transaction-service#134]
**Describe the bug**
I would expected that executed transaction are ordered by nonce (highest nonce first). This is equivalent to sort by the executed timestamp, but it seems in cases where the transactions have the same executed timestamp the nonce is not taken into account.

**To Reproduce**
Check: https://safe-transaction.mainnet.staging.gnosisdev.com/api/v1/safes/0x2C7b032d04CEFd6Fb910A27cCf0D8913C4Fa16a8/all-transactions/ -> nonce 1 is before nonce 0

**Expected behavior**
As a secondary sort after the executed timestamp the nonce should be taken into account

**Comment by Uxio0** [comment]
There's an edge case for multisig transactions mined in the same ethereum transaction

**Comment by Uxio0** [comment]
I checked the endpoint, it's fixed
