### ISSUE TITLE
Add additional fiat conversion oracles

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-transaction-service#135]
**Describe the bug**
Fiat value of yCurve token is 0

**To Reproduce**
https://safe-transaction.gnosis.io/api/v1/safes/0xFEB4acf3df3cDEA7399794D0869ef76A6EfAff52/balances/usd/

The response at the time i'm writing the ticket:
```
[
  {
    "tokenAddress": "0xdF5e0e81Dff6FAF3A7e52BA697820c5e32D806A8",
    "token": {
      "name": "Curve.fi yDAI/yUSDC/yUSDT/yTUSD",
      "symbol": "yDAI+yUSDC+yUSDT+yTUSD",
      "decimals": 18,
      "logoUri": "https://gnosis-safe-token-logos.s3.amazonaws.com/0xdF5e0e81Dff6FAF3A7e52BA697820c5e32D806A8.png"
    },
    "balance": "139276488795081812837140",
    "balanceUsd": "0.0",
    "usdConversion": "0.0"
  }
]
```

**Expected behavior**
The user expected the value to be somewhat close to this source https://www.coingecko.com/en/coins/lp-ycurve

**Additional context**
Reported by our user in telegram https://t.me/GnosisSafe/6102

**Comment by rmeissner** [comment]
I would say this is a feature request. We should check if we have alternative oracles or conversion rate source (e.g. Zerion or coingecko). Currently we expect that a token has a price either on Kyber, Uniswap or Kraken.

**Comment by Uxio0** [comment]
> I would say this is a feature request. We should check if we have alternative oracles or conversion rate source (e.g. Zerion or coingecko). Currently we expect that a token has a price either on Kyber, Uniswap or Kraken.

Automatic price estimation uses Kyber and Uniswap. Kraken is just used for ETH/DAI. I've checked and there's no price for that token on those platforms, so we need to decide if more oracles must be added to the service, but this would be another ticket. What do you think @tschubotz @lukasschor , is this required?

**Comment by tschubotz** [comment]
Hmm. I think it would be nice to have prices for most used tokens.

**Comment by lukasschor** [comment]
This has come up quite often recently where tokens (especially DeFi / Pool tokens) where valued at 0 USD. It would indeed be good to have more price oracles to cover these.

**Comment by rmeissner** [comment]
There is some research requires to find potential oracles.

New potential oracles:
- Uniswap v2
- ...

**Comment by Uxio0** [comment]
> New potential oracles:
> 
> * Uniswap v2

FYI, Uniswap V2 was added 2 weeks ago. Now the oracles supported are:

**Comment by tschubotz** [comment]
> Kraken (for ETHUSD)

Are we using Kraken for ETHUSD or for DAIUSD? (https://gnosisinc.slack.com/archives/CQB729LLF/p1601303396122100?thread_ts=1601303359.121900&cid=CQB729LLF)

**Comment by tschubotz** [comment]
I recently checked how many prices are missing.
https://docs.google.com/spreadsheets/d/1AdIG21NLmTqrvKkG0w3guWMFGURZsbEqzK_VsZ8I0gE/edit#gid=0 From the top 100 tokens in Safes (by number of Safes that hold this token), only aUSDC and idleUSDCYield don't have a price. So currently, I would not consider this important enough to add additional oracle. Hence I would close this ticket until this changes and/or more users provide feedback that they are missing a token price.

**Comment by Uxio0** [comment]
> Are we using Kraken for ETHUSD or for DAIUSD? (https://gnosisinc.slack.com/archives/CQB729LLF/p1601303396122100?thread_ts=1601303359.121900&cid=CQB729LLF)

I've just checked, it's ETHUSD, sorry for the typo
