### ISSUE TITLE
Structure of "DecodedValue" issues

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-transaction-service#137]
**Describe the bug**
Parameters contain `decodedValue` which seems to represent internal transactions. The `operation` field is serialised as `CALL` string, which is generally represented as `0` int value. Additionally, each internal transaction contains a field named `decodedData`, which in other circumstances it is named `dataDecoded`. Optionally, to follow the same convention, it would also make sense to change `decodedValue` to `valueDecoded`.

**To Reproduce**
1. Request https://safe-transaction.rinkeby.gnosis.io/api/v1/safes/0x1230B3d59858296A31053C1b8562Ecf89A2f888b/all-transactions/?&trusted=true
2. Find transaction with `safeTxHash` = `0xe1da4ef7552069404077a1c2d1c007629b263ed614fbeea426572c7dfe8a5771`

**Expected behavior**

**Additional context**
```json
parameters": [
          {
            "name": "transactions",
            "type": "bytes",
            "value": "0x00d9ba894e0097f8cc2bbc9d24d308b98e36dc6d0200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044a9059cbb000000000000000000000000938bae50a210b80ea233112800cd5bc2e764430000000000000000000000000000000000000000000000000000038d7ea4c6800000d9ba894e0097f8cc2bbc9d24d308b98e36dc6d0200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044a9059cbb000000000000000000000000938bae50a210b80ea233112800cd5bc2e764430000000000000000000000000000000000000000000000000000038d7ea4c6800000d9ba894e0097f8cc2bbc9d24d308b98e36dc6d0200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044a9059cbb000000000000000000000000938bae50a210b80ea233112800cd5bc2e764430000000000000000000000000000000000000000000000000000038d7ea4c68000",
            "decodedValue": [
              {
                "operation": "CALL",
                "to": "0xD9BA894E0097f8cC2BBc9D24D308b98e36dc6D02",
                "value": 0,
                "data": "0xa9059cbb000000000000000000000000938bae50a210b80ea233112800cd5bc2e764430000000000000000000000000000000000000000000000000000038d7ea4c68000",
                "decodedData": {
                  "method": "transfer",
                  "parameters": [
                    {
                      "name": "to",
                      "type": "address",
                      "value": "0x938bae50a210b80EA233112800Cd5Bc2e7644300"
                    },
                    {
                      "name": "value",
                      "type": "uint256",
                      "value": "1000000000000000"
                    }
                  ]
                }
              },
...
```

**Comment by Uxio0** [comment]
@jpalvarezl You are right, I didn't realize that I used different naming. Then, I will:

- Rename all `decodedData` to `dataDecoded`
- Rename all `decodedValue` to `valueDecoded`
- `operation` value (number) instead of string. e.g. `0` instead of `CALL`

Are you ok with this @dasanra @mikheevm @jpalvarezl @DmitryBespalov?

**Comment by mikheevm** [comment]
@fernandoomg @agupane could you please check this?

**Comment by DmitryBespalov** [comment]
@Uxio0 @jpalvarezl looks good to me

**Comment by mikheevm** [comment]
@Uxio0 the PR is ready on our side, could you please ping once so we merge it once the changes are live on the backend?

**Comment by Uxio0** [comment]
Hi @mikheevm, I reviewed the PR and couldn't find any changes to `Operation`, and it changed from string to number
