### ISSUE TITLE
Make services available for xDai

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-transaction-service#138]
- [x] contracts are required on xDai chain
  - `ProxyFactory` and `MasterCopy` should be on the same address as on other networks
- [x] xDai tracing node
- [x] xDai transaction service

**Comment by Uxio0** [comment]
xDai tracing node is already syncing, it's still on 2019

**Comment by Uxio0** [comment]
https://safe-transaction.xdai.gnosis.io/
