### ISSUE TITLE
Add support for EWF chains

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-transaction-service#139]
Run service for EWF chains
- Volta (EWF testnet)
- EWF mainnet

- [x] Tracing node (EWF)
- [x] Tracing node (Volta)
- [x] Transaction service (EWF)
- [x] Transaction service (Volta)

### Details
- **1.2.0** Contracts are on same addresses as in other networks
- Soft deadline: End of september
- TBD

**Comment by Uxio0** [comment]
Services are up and running:

- https://safe-transaction.volta.gnosis.io/
- https://safe-transaction.ewc.gnosis.io/
