### ISSUE TITLE
Feature: Return safe tx hash

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-transaction-service#14]
**What is needed?**

Return safe tx hash like in relay service with get request

**Why is it needed?**
On the frontend we need something unique to distinguish transactions

**When is it needed?**
The faster the better :see_no_evil:

**Comment by Uxio0** [comment]
Service will return `safeTxHash` on the response

**Comment by Uxio0** [comment]
@mikheevm Can you confirm is it working?

**Comment by mikheevm** [comment]
Yes, it is :) thank you
