### ISSUE TITLE
Confirmation sorting order for MultisigTransaction

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-transaction-service#141]
**Describe the bug**
The confirmation list for Multisig Transaction are sorted differently depending from which endpoint the values are returned.

**To Reproduce**
Examine the JSON returned by https://safe-transaction.staging.gnosisdev.com/api/v1/transactions/0x0ef685fb7984d7314c1368497e1b0c73016066bec41f966d32f18354b88fbd46/
and the JSON returned by this: https://safe-transaction.staging.gnosisdev.com/api/v1/safes/0x1230B3d59858296A31053C1b8562Ecf89A2f888b/all-transactions/

For the 2nd, look for the transaction with `safeTxHash` equals to `0x0ef685fb7984d7314c1368497e1b0c73016066bec41f966d32f18354b88fbd46` (at the time of writing this issue, it is the 2nd entry in the 1st page of data)

**Expected behavior**
Confirmation sorting order should be consistent across endpoints

**Comment by Uxio0** [comment]
Hi @jpalvarezl, I see the same ordering, but you are right. As no ordering field is defined when querying from database ordering may not be stable. By default confirmations are now sorted by creation date
