### ISSUE TITLE
No push when ETH/tokens are transferred as part of internal tx made by the Safe

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#149]
# What is needed?
Don't send push notification when ETH/tokens are transferred as part of internal tx made by the Safe

# Background
- Currently, we send a push, whenever ETH/tokens are transferred into the Safe. No matter if this was done from some other account or if this was perhaps triggered by a custom txs made by the Safe itself.
- The push currently opens the tx list.
- So currently, 2 pushes are sent: 1 for a successful tx, another 1 for incoming tokens.
- Problem is: We decided that these internal token transfers won't be displayed on the tx list. So there's nothing to see.

- Example: https://etherscan.io/tx/0x5a9f279b9b698a320f83ef0712f5b1c3b6424628d40b7efca549e22d205479fd
  - tx made by the Safe
  - 60 ETH transferred to the Safe
  - on the tx list, only the tx ist displayed, not the incoming tokens.

# Task

- Only send ETH/token pushes when they weren't triggered by a tx from some account other than the Safe.

(Long term, on mobile and web we should display the transferred tokens on the tx details, but that's for a separate issue)

**Comment by Uxio0** [comment]
So, if I'm understanding well, if the transaction is triggered by the owners of the Safe (a Safe Multisig Transaction) transferring something into that same Safe, we shouldn't display a notification of incoming ETH/Tokens, right @tschubotz?

**Comment by tschubotz** [comment]
> So, if I'm understanding well, if the transaction is triggered by the owners of the Safe (a Safe Multisig Transaction) transferring something into that same Safe, we shouldn't display a notification of incoming ETH/Tokens, right @tschubotz?

Exactly.

And this is due to the following 2 reasons:
- This triggers already another push: "Successful tx". 
- The clients only display 1 row on the tx list: The successful tx.

**Comment by rmeissner** [comment]
Just to clearify: if we base this on the account submitting the tx (e.g. `tx.origin`) being an owner, than this will not work if you use an relay, right?

**Comment by Uxio0** [comment]
I guess it will be based on if an event was generated in a transaction sending a multisig transaction from that `to` address. It would break events for multiple multisig sent in the same transaction, but I think that's a very edge case

**Comment by rmeissner** [comment]
> It would break events for multiple multisig sent in the same transaction, but I think that's a very edge case

But then this would also break the logic in the `all-transactions` endpoint (where transfers are put into the multisig transaction), so it should be fine :)

**Comment by Uxio0** [comment]
This is already on staging @tschubotz
