### ISSUE TITLE
Sort asset balances endpoints by default by Token name and ETH on top

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#150]
# What is needed?
Sort asset balances endpoints by default by Token name. Eth should always come first.

# Background

Currently, there is no default sorting on mobile. The clients just display assets in the order the backend provides them. That looks messy for long lists.

# Related issues
- gnosis/safe-ios#555
- gnosis/safe-android#913

# Task / proposal

Implement sorting for 
`GET /safes​/{address}​/balances​/`
`GET ​/safes​/{address}​/balances​/usd​/`
- ETH should be first.
- Afterwards tokens, sorted by token name, asc.

**Comment by Uxio0** [comment]
@tschubotz Is this required also for the ERC721 collectibles endpoint?

**Comment by tschubotz** [comment]
> @tschubotz Is this required also for the ERC721 collectibles endpoint?

I mean, this would make it easier to find collectibles. 

Way more important are the coins/tokens but if it's doable for collectibles as well, then this one also, yes.

**Comment by rmeissner** [comment]
Gor the collectables the clients perform some grouping, right? So they resort anyways.

**Comment by Uxio0** [comment]
Ok, I would wait for collectibles until someone complains then

**Comment by tschubotz** [comment]
> Ok, I would wait for collectibles until someone complains then

👍

**Comment by tschubotz** [comment]
cc @liliya-soroka (only deployed to staging so far, I assume production early next week due to no deploys on Friday :) )

**Comment by Uxio0** [comment]
> cc @liliya-soroka (only deployed to staging so far, I assume production early next week due to no deploys on Friday :) )

That's right, I can do it on monday
