### ISSUE TITLE
Add ABI for AllowanceModule

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#156]
Add ABI for https://github.com/gnosis/safe-modules/blob/feature/allowances/allowances/contracts/AlowanceModule.sol so module txs get properly decoded.

**Comment by Uxio0** [comment]
Waiting for @rmeissner approval

**Comment by tschubotz** [comment]
@Uxio0 
Definitive version is deployed at https://etherscan.io/address/0xCFbFaC74C26F8647cBDb8c5caf80BB5b32E43134#code (Same address on all networks)

(https://github.com/gnosis/safe-modules/blob/master/allowances/networks.json)
