### ISSUE TITLE
Tokens not showing up in Safe

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#157]
**Describe the bug**
Tokens don't show up in Safe.

**To Reproduce**
(on Rinkeby)

1. Create new ERC20 token on https://vittominacori.github.io/erc20-generator/ with Metamask (I created a random token with 100 initial supply https://rinkeby.etherscan.io/token/0x0707cde3f1eb69e9e8d30ff2d06febd5ae7e2e51) 
2. Send 10 of those tokens to a Safe (I sent to 0xaE3c91c89153DEaC332Ab7BBd167164978638c30)
3. Tokens how up on https://rinkeby.etherscan.io/address/0xaE3c91c89153DEaC332Ab7BBd167164978638c30#tokentxns
4. Tokens **don't** show up on https://rinkeby.gnosis-safe.io/app/#/safes/0xaE3c91c89153DEaC332Ab7BBd167164978638c30/balances
5. I check https://safe-transaction.rinkeby.gnosis.io/api/v1/safes/0xaE3c91c89153DEaC332Ab7BBd167164978638c30/balances/usd/?exclude_spam=true&limit=3000 -> Tokens **don't** show up.
6. I check the tx service without the spam filter, i.e. https://safe-transaction.rinkeby.gnosis.io/api/v1/safes/0xaE3c91c89153DEaC332Ab7BBd167164978638c30/balances/usd/ -> Tokens **do** show up
7. Now I check again with the spam filter (https://safe-transaction.rinkeby.gnosis.io/api/v1/safes/0xaE3c91c89153DEaC332Ab7BBd167164978638c30/balances/usd/?exclude_spam=true&limit=3000) -> Tokens now **do** show up oO
8. Tokens now also show up on https://rinkeby.gnosis-safe.io/app/#/safes/0xaE3c91c89153DEaC332Ab7BBd167164978638c30/balances

**Expected behavior**
Tokens show up right away.

**Comment by tschubotz** [comment]
The issue exists for me even without deploying a new token. 

It's just important that the recipient Safe doesn't have this token yet.

**Comment by Uxio0** [comment]
@tschubotz A patch for this has been deployed now (commit 5d868c531b1845cb67205e7d2f67f0268fab84a5)

I will try to reproduce it now

**Comment by Uxio0** [comment]
It's working now @dasanra please let me know if you see this behaviour again, I will deploy a patch to production tomorrow

**Comment by tschubotz** [comment]
I can confirm, issue is fixed on https://safe-transaction.staging.gnosisdev.com/

Thanks Uxio! :)

**Comment by rekt0x** [comment]
Hey, I just experienced this issue again: New safe and the assets are not showing up.

https://safe-client.safe.global/v1/chains/1/safes/0x123...456/balances/usd also only shows 0 ETH and no other tokens (but there are other tokens in it):
```
{"fiatTotal":"0","items":[{"tokenInfo":{"type":"NATIVE_TOKEN","address":"0x0000000000000000000000000000000000000000","decimals":18,"symbol":"ETH","name":"Ether","logoUri":"https://safe-transaction-assets.safe.global/chains/1/currency_logo.png"},"balance":"0","fiatBalance":"0.00000","fiatConversion":"1208.47"}]}
```

Any ideas?
