### ISSUE TITLE
Profile endpoint times

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#158]
# What is needed?
Know how long takes for an endpoint to return the result, so we can find bottlenecks

# Proposed solutions
- Add elapsed time to the logs
- Parse them on Kibana

**Comment by Uxio0** [comment]
Implemented on staging, pending on devops to move it to production

**Comment by tschubotz** [comment]
@Uxio0 is there a Kibana dashboard for this? 
I only found https://logs.gnosis.io/app/kibana#/dashboard/1e7efa80-8dfa-11ea-91fe-73ebc1c30edf

**Comment by Uxio0** [comment]
This is the dashboard, but there are some issues with the logs not being filtered devops are checking: https://logs.gnosis.io/app/kibana#/dashboard/faa19a80-5ef7-11eb-af57-6961fcf94ae7
