### ISSUE TITLE
Add RLY token

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#159]
Could you please add the RLY token to our token list on mainnet?

https://etherscan.io/address/0xf1f955016ecbcd7321c7266bccfb96c68ea5e49b

(Yes, created just 1 day ago. It's for an upcoming IDO.)

Logo:
[rly-t.svg.zip](https://github.com/gnosis/safe-transaction-service/files/5339799/rly-t.svg.zip)

**Comment by Uxio0** [comment]
Done
