### ISSUE TITLE
Collectible group icons/images not displayed for all collectibles types (Except ENS)

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#167]
# Context

- We compared our collectibles API against OpenSea in terms of completeness of the info: https://docs.google.com/spreadsheets/d/15Ul00Vd-wvr0qLwBXE3hdYraI8a0MqOG9136MpsDMck/edit?ts=5f9ae5eb#gid=0
- Looks quite good, except 2 issues:
  - Group images are not present (only for ENS)
  - CryptoKitties don't work (Part of #172)

# Task

- Please double check, why group images are not displayed. (According to Uxio it should be part of the ERC721 Metadata standard)
  - If it can't be fixed via the Metadata standard, let's think about other solutions, e.g. pulling the info from OpenSea or setting it manually like we do it for ERC20 tokens.

# Old ticket description

Some ERC721 tokens don't comply to the standard, yet OpenSea has information for them. We agreed on just using blockchain public information to avoid depending on a centralized service.

Should we add OpenSea as a new source for the collectibles in the backend (at least until they limit or close the API)?

# Updates

- Nov 2, Tobi: Update ticket description and content after concluding research.

**Comment by tschubotz** [comment]
Just for the record:
Not yet complete, but here's the preliminary result https://docs.google.com/spreadsheets/d/15Ul00Vd-wvr0qLwBXE3hdYraI8a0MqOG9136MpsDMck/edit?ts=5f9ae5eb#gid=0
From the top types of NFTs currently held in Safes, there’s only 2 were OpenSea has more info. And they are not standard.
Based on this, there’s imo no need to integrate OpenSea. 

There is a [Slack](https://gnosisinc.slack.com/archives/CQB729LLF/p1604072853391800) conversation about this.
