### ISSUE TITLE
[Documentation] Add documentation for working with delegates

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#168]

**Comment by tschubotz** [comment]
This could make for a great brief Tutorial at https://docs.gnosis.io/safe/docs/services_tutorials/ :)

**Comment by Uxio0** [comment]
I think we can close it, right? cc: @jpalvarezl @rmeissner 

https://docs.gnosis.io/safe/docs/tutorial_tx_service_set_delegate/
