### ISSUE TITLE
500 for fetching collectibles on volta

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#170]
**Describe the bug**
500 for fetching collectibles on volta

**To Reproduce**
1. Open https://safe-transaction.volta.gnosis.io/api/v1/safes/0x855cB0Bb58a5413969BA455f860FAFd7FA66F883/collectibles/

**Expected behavior**
See 1 NFT

**Comment by Uxio0** [comment]
This was fixed by 1a3f0732e8626ec1f393a26d40dc68a214e7dfc1 ,could you confirm @tschubotz ?

**Comment by tschubotz** [comment]
Confirm!
Thanks :)
