### ISSUE TITLE
TestNFT not showing up on xDai

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#171]
**Describe the bug**

**To Reproduce**

https://blockscout.com/poa/xdai/address/0x82FC6069FB9290F98c6ae02b6cfb7B6aB0ab97bf/tokens -> TestNFT

https://safe-transaction.xdai.gnosis.io/api/v1/safes/0x82FC6069FB9290F98c6ae02b6cfb7B6aB0ab97bf/collectibles/ -> No Collectibles. 

That's the NFT contract: https://blockscout.com/poa/xdai/address/0xB38dcaD8FEdABeA9EBE304Ad356FD64a15485069/contracts

**Expected behavior**

NFT shows up

**Additional context**

That's the same NFT contract like on Volta in #170, but there I actually even see an incoming TNFT in the tx list.

**Comment by francovenica** [comment]
I tried with the 2 contracts you created, I minted a token for volta and one for xDai and it worked for me. They showed in the collectibles tabs and I was able to send the token to other safes

Volta safe were I minted the token: https://pr1537--safereact.review.gnosisdev.com/volta/app/#/safes/0xE8407958dE3E24351222dc00D942457CcC1C0c73/transactions


Volta safe were I sent the token afterwards: https://pr1537--safereact.review.gnosisdev.com/volta/app/#/safes/0x538622a690A651D852277c07334dC3377E22cdeF/balances/collectibles

xdai safe where i minted the token: https://pr1537--safereact.review.gnosisdev.com/xdai/app/#/safes/0x8B22bAf910E83a66FacF8539AFC125cBc026059b/transactions

xdai safe where i sent the token: https://pr1537--safereact.review.gnosisdev.com/xdai/app/#/safes/0x05d6e4d008CdFeDcf4d03F390E8E6A2c58aBE8DE/transactions

Volta NFT Minter
0xdae6a48b83b3D4F8a2AcB6C5E77ff9e0B508491A
xDAI NFT Minter
0xB38dcaD8FEdABeA9EBE304Ad356FD64a15485069

**Comment by tschubotz** [comment]
@francovenica thanks!
Seems this is related to the indexing not being up to date. Could that be @Uxio0 ? 
Either way, closing the issue since it seems fixed and cannot be reproduced.

**Comment by Uxio0** [comment]
Hi @tschubotz @francovenica, indexing might not be up to date at that time, because the NFT it's showing now and I didn't change anything: https://safe-transaction.xdai.gnosis.io/api/v1/safes/0x82FC6069FB9290F98c6ae02b6cfb7B6aB0ab97bf/collectibles/

**Comment by Uxio0** [comment]
> @francovenica thanks!
> Seems this is related to the indexing not being up to date. Could that be @Uxio0 ?
> Either way, closing the issue since it seems fixed and cannot be reproduced.

Yes, It looks like an indexing issue at that time. Last week we were doing a lot of changes on the services and the machines (resources) so it makes sense
