### ISSUE TITLE
Token with `decimals=null` is appearing on the `/balances/` endpoint

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#173]
**Describe the bug**
Token with `decimals=null` is appearing on the `/balances/` endpoint

**Comment by liliya-soroka** [comment]
confirmed and check on both clients in the version 2.4.0 - The balance page is loaded
The balance page is not loaded in the 2.5.0 rc , as client-gateway with total balance is not deployed to production ( not a problem as only 2.4.0 is available for the real users
