### ISSUE TITLE
Prod/Mainnet: 503 or timeout when the transaction list is called

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-transaction-service#176]
**Describe the bug**
https://safe-client.mainnet.gnosis.io/v1/safes/0x5CC3a4C846aB8b0B78a729b8B1a50e2E0BB66740/transactions or https://safe-client-mainnet.gnosis.io/v1/safes/0x5CC3a4C846aB8b0B78a729b8B1a50e2E0BB66740/transactions => 
{"code":1337,"message":"reqwest::Error { kind: Request, url: \"https://safe-transaction.gnosis.io/api/v1/safes/0x5CC3a4C846aB8b0B78a729b8B1a50e2E0BB66740/all-transactions/?\", source: TimedOut }"}
Sometimes 502 or 503 are returned instead of timeout
No successful tries for the transaction list for an hour

Seems that the back-end is very slow

**Comment by Uxio0** [comment]
It's fixed for now, but I will keep working on this
