### ISSUE TITLE
Decode MakerDAO transactions

### ISSUE THREAD

**Issue by denisgranha** [gnosis/safe-transaction-service#182]
You can find a file with all the abi's here [https://changelog.makerdao.com/releases/mainnet/1.1.4/abi/index.html](https://changelog.makerdao.com/releases/mainnet/1.1.4/abi/index.html)

And a list of addresses: [https://changelog.makerdao.com/releases/mainnet/active/contracts.json](https://changelog.makerdao.com/releases/mainnet/active/contracts.json)

**Comment by Uxio0** [comment]
I added the abis using this script, for future reference:

```

**Comment by Uxio0** [comment]
@lukasschor @tschubotz @rmeissner I think adding all this 128 Abis (https://changelog.makerdao.com/releases/mainnet/1.1.4/abi/mainnet_abi_1.1.4.zip) should cover all the MakerDao related transactions 😁
