### ISSUE TITLE
Add deployer information to master copies endpoint

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#183]
# What is needed?
Project information on master copies endpoint

# Background
`api/v1/about/master-copies/` returns

```js
{
  address: '0x',
  version: '1.1.1'
}
```

A field to tell projects apart would be desired, like:
```js
{
  address: '0x',
  version: '1.1.1',
  deployer: 'Circles'
}
```

**Comment by tschubotz** [comment]
Instead of `CIRCLE` please use `Circles` (putting emphasis on the `s`, I don't mind all caps) since that's how the project is called :) 
https://circles.garden
