### ISSUE TITLE
Update mStable related token logos

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#185]
# Context

The mStable team reach out to us about the logos and names used for their tokens.

# Task

### MTA

- https://safe-transaction.gnosis.io/api/v1/tokens/?symbol=MTA
- `0xa3BeD4E1c75D00fa6f4E5E6922DB7261B5E9AcD2`
- Please change the logo to `mstable_logo_circle_m_black.png` from the mAssets icon list below. (Black circle with white underscored "m")

### mUSD 

- https://safe-transaction.gnosis.io/api/v1/tokens/?symbol=mUSD
- `0xe2f2a5C287993345a840Db3B0845fbC70f5935a5`
- Please change the logo to `mstable_logo_circle_dollar_black.png` from the mAssets icon list below. (Black circle with white $)

# Misc

mAssets icons can be found here: https://docs.mstable.org/mstable-assets/brand-assets

**Comment by Uxio0** [comment]
Done 👍
