### ISSUE TITLE
Expose last indexed block from transaction service

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-transaction-service#189]
https://github.com/gnosis/safe-client-gateway/issues/37 is caused by a difference of the state that has been indexed and the state that is available to query via our nodes. Therefore it would be good to know until what block the state has already been indexed, so that the state of the Safe can be queried using that block.

Also it would allow us to check if there are issues related to indexing (support).

## Discussion points
- We index different mastercopies independently, should we return the last indexed block for each mastercopy or a minimum of all.

**Comment by Uxio0** [comment]
Last indexed block for every master copy is now exposed on `/api/v1/about/master-copies/` endpoint
