### ISSUE TITLE
Change OWL icons on xDai

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#192]
# What is needed?
There are 2 OWL tokens, only 1 can be used with GP on xDai. That one should have the correct icon.

# Background

See [Slack](https://gnosisinc.slack.com/archives/C63LQTGNB/p1606854572427800)

# Request

Please remove the token icon from 

Please add the OWL token icon to https://blockscout.com/poa/xdai/tokens/0x0905Ab807F8FD040255F0cF8fa14756c1D824931/token-transfers

Please remove the icon from https://blockscout.com/poa/xdai/tokens/0x750eCf8c11867Ce5Dbc556592c5bb1E0C6d16538/token-transfers

**Comment by Uxio0** [comment]
Ready!
