### ISSUE TITLE
Find ways to get more fiat prices

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#194]
# Background:

- Slack: https://gnosisinc.slack.com/archives/CQB729LLF/p1607352199373200
- I checked for how many tokens in Safes we have fiat prices: https://docs.google.com/spreadsheets/d/1AdIG21NLmTqrvKkG0w3guWMFGURZsbEqzK_VsZ8I0gE/edit#gid=1075599800
- Aave and pool tokens aren't covered

# Task:
Please find a way to get the fiat prices for the following tokens types:

1: Aave tokens (Primarily aUSDC, aSNX)
2: Uniswap V2 pool tokens (UNI-V2)
3: Curve pool tokens (crvRenWBTC, tbtc/sbtcCrv, crvPlain3andSUSD, 3Crv)
4: Balancer pool tokens (BPT)
5: Yearn finance related tokens (yUSDC, most others have a price already via our on chain oracles)

# Idea:

https://github.com/zeriontech/defi-sdk could help with this potentially.

(Please split this ticket up into separate ones in case it's too big.)

**Comment by rmeissner** [comment]
We should check tradeoffs between on-chain "trustless" oracles, and off-chain oracles (trusted offchain vs aggregators like coin gecko)

Do we have any plan to solve this.

**Comment by Uxio0** [comment]
Biggest problem about coingecko and similars is that they don't allow searching for an address, just the symbol/name (and as we know it doesn't match all the time). I have to check how accurate could be using off-chain oracles, because until now we have just used that kind of oracles (kraken, binance...) for known tokens and in a defined way.

**Comment by tschubotz** [comment]
We could also ask zerion (there's a shared Slack channel) on how they do it. Perhaps there's even options to collaborate?

**Comment by Uxio0** [comment]
After some reading I will try Chainlink first and check the results they provide. If it works well it might help us with issue #195

**Comment by Uxio0** [comment]
I'm still trying to find out a decentralized way to calculate prices for pools like Balancer or Uniswap. Best solution I could find (centralized) is coingecko:

```bash
curl -X GET "https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=0xdf5e0e81dff6faf3a7e52ba697820c5e32d806a8&vs_currencies=usd" -H "accept: application/json"
```

I implemented SushiSwap as it was really straightforward having Uniswap V2 already, what should be the priority for checking prices? (current is Kyber, Uniswap V2, Uniswap V1). I would propose Kyber, Uniswap V2, SushiSwap, Uniswap V1 and then coingecko if we decide to use it.

**Comment by tschubotz** [comment]
Great to have Sushiswap now also!

The DefiSdk couldn't be used for getting fiat prices? Would it be possible to go via the value of underlying Asset? i.e. for aDAI, perhaps we get the amount of DAI that equals to via the defi sdk and then we have an oracle for DAI?

But generally what you propose, with coingecko as the last resort I think sounds good! Do we need an API key from them?

**Comment by Uxio0** [comment]
I've just implemented an oracle for curve pools.

> The DefiSdk couldn't be used for getting fiat prices? 

No, unless I'm missing something

> Would it be possible to go via the value of underlying Asset? i.e. for aDAI, perhaps we get the amount of DAI that equals to via the defi sdk and then we have an oracle for DAI?

I don't think so. I couldn't find any way to get info on the token without having to know which adapter is supporting it. Even if possible it would be very tedious to do so as it would be a different logic depending on the underlying asset (just a token, 2 tokens...), so it would be a one by one case and not a deterministic way to get the price. I think coingecko can fill that gap.

> Do we need an API key from them?
https://www.coingecko.com/en/api it says `Rate Limit: 100 requests/minute`. With caching I think it should be enough, but I ge can get a "pro" api key (I don't know if it exist) it will be awesome

**Comment by tschubotz** [comment]
> I don't think so. I couldn't find any way to get info on the token without having to know which adapter is supporting it

I also didn't find way

> https://www.coingecko.com/en/api it says Rate Limit: 100 requests/minute. With caching I think it should be enough, but if we can get a "pro" api key (I don't know if it exists) it will be awesome

Right, with caching it should be fine probably. I didn't find something about a pro account. Let's start with the free tier and we can reach out in case that isn't enough.
Dune analytics uses e.g. https://coinpaprika.com/api/ for price info.

**Comment by Uxio0** [comment]
I consider this ticket should be closed now. I've updated and created new oracles, plus refactoring the old ones:
- Refactor Kraken, Binance and Kucoin oracles in their own classes and test them in an easier way
- Maintain an `http` session for some oracles when possible, so `http` connection is reused
- Create new oracles for Curve, Balancer and Mooniswap pool tokens and add logic to calculate price of pool tokens for Uniswap V2 oracle
- Create new oracle for Sushiswap
- Add a new oracle using Coingecko API as the last resource if price cannot be fetched anywhere else
- Disable every price oracle but Kyber/Uniswap V2 for other networks different from Mainnet.

I think we should be covering now more prices than the rest of the wallets. What do you think @tschubotz @rmeissner ?

**Comment by tschubotz** [comment]
> Disable every price oracle but Kyber/Uniswap V2 for other networks different from Mainnet.

so on xdai, volta, ewf they are enabled?

> I think we should be covering now more prices than the rest of the wallets. What do you think @tschubotz @rmeissner ?

I didn't verify that claim, however I think we are good for now and close this ticket. If more prices are needed, let's handle that separately :)

**Comment by Uxio0** [comment]
> so on xdai, volta, ewf they are enabled?

Good point. They are enabled but as there's no Kyber/Uniswap on that networks it doesn't work

> I didn't verify that claim, however I think we are good for now and close this ticket. If more prices are needed, let's handle that separately :)

👍
