### ISSUE TITLE
More robust on chain price oracles

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#195]
# Background:

At least one Safe had a crazy fiat balance due to the Uniswap price oracle reporting an unrealistic fiat balance. Reason was the low liquidity. More info here: https://gnosisinc.slack.com/archives/C63LQTGNB/p1607072103493900

# Task/Ask:

Please make fiat balances more robust by filtering out unrealistic values.

# Idea: 

Filter on-chain price oracles by liquidity i.e. discard low liquid one's. in the example above, the pool had 0.13USD liquidity.

**Comment by tschubotz** [comment]
Seems like this issue came up again with stkAAVE https://gnosisinc.slack.com/archives/CQB729LLF/p1611148568153300

**Comment by Uxio0** [comment]
I think the issue with the liquidity of tokens should be fixed now. I implemented a basic liquidity check: Every token of the uniswap pair needs at least 1 full unit of the token for the price to be valid (10**decimals).

I'm trying with `Uniswap V2 DAI/WETH Pool` (0xA478c2975Ab1Ea89e8196811F51A7B7Ade33eB11):
`CannotGetPriceFromOracle: Not enough liquidity for pair token_1=0xA478c2975Ab1Ea89e8196811F51A7B7Ade33eB11`

**Comment by tschubotz** [comment]
> I think the issue with the liquidity of tokens should be fixed now. 

Is the fix already live?

> Every token of the uniswap pair needs at least 1 full unit of the token for the price to be valid (10**decimals).

This sounds reasonable to me! We could even set the limit to 10 or so in my opinion in order to be even more robust.

**Comment by Uxio0** [comment]
> Is the fix already live?

It's ready, but I was waiting for your input

> This sounds reasonable to me! We could even set the limit to 10 or so in my opinion in order to be even more robust.

**Comment by tschubotz** [comment]
> Maybe we leave out some coins with small caps. That will require at least 10Eth to be deposited (with the current high price). But we can do that if you think that would be better, I'm not an expert on that 😉

hm ya, I was thinking if there isn't even 10ETH in there, then it's anyway not reliable ;) 

But seems like a lower limit already fixes it for the 2 examples above. Then let's go with a lower limit of `2 * (10**decimals)` for now and we can adapt later. :)

Let me know when you have it on staging, then I'll check a couple of Safes to see how it looks.
