### ISSUE TITLE
Use better names for Uniswap V2 pool tokens

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#196]
# Background/ context:

Currently, all Uniswap V2 tokens have the same name: "Uniswap V2": https://safe-transaction.gnosis.io/api/v1/tokens/?name=Uniswap%20V2&UNI-V2

It's because that's the actual on chain name of these tokens. That makes it impossible to tell them apart in the Safe UI.

# Task/goal:
It should be possible to tell them apart in the UI.

# Idea:

Use https://github.com/zeriontech/defi-sdk to get the names of the pool

https://github.com/zeriontech/defi-sdk/blob/master/contracts/adapters/uniswap/UniswapV2TokenAdapter.sol

is deployed on 

https://etherscan.io/address/0x6C5D49157863f942A5E6115aaEAb7d6A67a852d3#readContract

### Example: getMetaData(0x3fd4Cf9303c4BC9E13772618828712C8EaC7Dd2F) -> Let's set the token name "Uniswap V2 BNT/WETH Pool

**Comment by rmeissner** [comment]
IIRC then it is fine to use aggregators such as CoinGecko if we don't find another solution (right @tschubotz ?)

**Comment by Uxio0** [comment]
@tschubotz Token symbol should remain `UNI-V2`, right?

**Comment by tschubotz** [comment]
> @tschubotz Token symbol should remain `UNI-V2`, right?

That's what I was thinking so far, yes. The thing is though, on mobile we only display token symbols so far 🤔 
Other exchanges such as mooniswap encode the pair e.g. `MOON-V1-DAI-USDC`
Hence I'm think if it would make sense to also do `UNI-V2-DAI-USDC`

What do you think? Would that make sense?

**Comment by Uxio0** [comment]
If possible I would prefer to just modify the `name` and leave the `symbol` as it is. It's very easy for me to modify both, but `symbol` usually should be something small and for some cases I have the feeling that we will be getting a long string, maybe breaking some of our client apps UX that count on symbol being something small.

**Comment by tschubotz** [comment]
Okay, let's keep this separate. Let's just modify the `name` for now and leave `symbol` as is.
Thereby symbol remains really the on-chain symbol like before.

In case we want to modify symbol, let's discuss separately in a different issue :)
