### ISSUE TITLE
Properly index WETH/wxDAI deposit and withdraw events.

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#197]
# Background

- Currently, WETH deposits and withdrawals are not taken into account for the assets in a Safe.
- That is expected behavior at this point.
- We only index ERC20 Transfer events.
- Recently, the reports of users missing their freshly minted WETH (or wxDAI) went up.

# Task / ask

- WETH and wxDAI Deposits / Withdrawals should be reflected in the assets overview properly.

# Misc

- WETH mainnet: https://etherscan.io/token/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
- WETH Rinkeby: https://rinkeby.etherscan.io/token/0xc778417e063141139fce010982780140aa0cd5ab
- wxDAI xdai: https://blockscout.com/poa/xdai/address/0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d/transactions

**Comment by Uxio0** [comment]
@tschubotz @lukasschor I've a proposal for this problem, ¿what do you think if I add a field to the tokens in database `force_balance_check` so it forces checking balance for every person even if the service does not see events for those tokens? That way you would be able to add in the panel without my interventation the currencies people are having trouble with.

Performance wise it wouldn't have any noticeable impact as long as we don't enable a lot

**Comment by tschubotz** [comment]
Would this balance check we done everytime an asset/balance request is made?

(I can't really judge if this is a good solution, tech-wise. @rmeissner would be the better person to comment I guess. :) )

**Comment by Uxio0** [comment]
> Would this balance check we done everytime an asset/balance request is made?
Yes, but it's batched with the other tokens, so it shouldn't be even noticeable

**Comment by tschubotz** [comment]
I mean that seems like it would fix the issue that we have with WETH balances. So it sounds good to me :)

**Comment by Uxio0** [comment]
Closed by 1c51aa50a4cfdce470bf5a1d5230aaad848a3bd0
