### ISSUE TITLE
Inconsistent state

### ISSUE THREAD

**Issue by denisgranha** [gnosis/safe-transaction-service#205]
**Describe the bug**
The safe with address 0x3fa80C890B76f17B53C9E173a283C1eB8E3C93d4 had a transaction with nonce 98 marked as not executed but after a reindex it was marked as executed. This issue didn't seem to trigger error logs in the service and it saved in the DB a newer tx with nonce 99 as executed eventhough this was not posible as the nonce on-chain was 99 (if the nonce 99 were executed it would have been 100)

**To Reproduce**
I attach some .json files from the API endpoints from before and after the incident. (This was performed on staging and prod, being the reindex done on staging first) 

[safe-json.zip](https://github.com/gnosis/safe-transaction-service/files/5750329/safe-json.zip)

**Expected behavior**
Match the state after reindex

**Additional context**
There is some additional context from the user perspective on discord

**Comment by Uxio0** [comment]
@rmeissner @denisgranha Everything seems alright since the hotfix, I have checked right now and not a single Safe is out of sync. I will close it for now

**Comment by Uxio0** [comment]
@rmeissner @denisgranha I've just checked, everything is still good, not a single Safe out of sync. It seems like it was indeed a caching issue

**Comment by denisgranha** [comment]
cool, thx @Uxio0
