### ISSUE TITLE
Many (all?) contracts have the wrong ABI connected.

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#206]
**Describe the bug**
I saw that many contract have a wrong ABI connected on mainnet staging. Not sure if that's an issue but it confused me when browsing the admin interface.

**To Reproduce**

- https://safe-transaction.mainnet.staging.gnosisdev.com/admin/contracts/contract/0x0000000000013949F288172bD7E36837bDdC7211/change/?_changelist_filters=q%3D%26has_abi%3DYES
- Compare that to https://etherscan.io/address/0x0000000000013949F288172bD7E36837bDdC7211#code

-> Contract names differ. And also the ABIs differ.

(The same is true for all other contract I checked which was ~8)

**Expected behavior**

Contract name and ABI the same on Etherscan and our backend.

**Comment by Uxio0** [comment]
Looks like @tschubotz I will fix asap, it shouldn't take long

**Comment by Uxio0** [comment]
@tschubotz It looks ok now, could you confirm?

**Comment by tschubotz** [comment]
> @tschubotz It looks ok now, could you confirm?

I confirm. The ones I checked look good :)

**Comment by tschubotz** [comment]
Seems like there are still some issues with this. Here are examples:

Mesa
- https://etherscan.io/address/0x6f400810b62df8e13fded51be75ff5393eaa841f#code
- https://safe-transaction.mainnet.staging.gnosisdev.com/admin/contracts/contract/0x6f400810b62df8e13fded51be75ff5393eaa841f/change/
- Etherscan says: `BatchExchange`
- Our admin says `ERC721FullBatchMint` and has a wrong ABI connected.

cBAT
- https://safe-transaction.mainnet.staging.gnosisdev.com/admin/contracts/contract/0x6c8c6b02e7b2be14d4fa6022dfd6d75921d90e4e/change/
- https://etherscan.io/address/0x6c8c6b02e7b2be14d4fa6022dfd6d75921d90e4e#code
- Etherscan says `CERC20`
- Our admin says `PayingProxy` and has a wrong ABI connected.

Let me know if I should go on a hunt for more examples.

**Comment by Uxio0** [comment]
Looks like we had some scraping issues and some contracts were not fixed, I'm triggering the scraping again

**Comment by Uxio0** [comment]
That was it, it should be ok now. Tomorrow I will move the contracts updated to production
