### ISSUE TITLE
Check the transaction service push notification for removed safe

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-transaction-service#207]
On iOS there's an issue with receiving confirmation requests for the removed safe (after unregister request - DELETE /api/v1/notifications/devices/{deviceID}/safes/{address}/): https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/782

Expected to not receive any notifications when safe was removed.

**Comment by Uxio0** [comment]
There was a missing check on the code, could you check it's working as supposed now?

**Comment by DmitryBespalov** [comment]
Looks like it is fixed.
