### ISSUE TITLE
Add displayName/logo for contracts

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#208]
Add new attributes to the contract model:
- `displayName` would allow to manually specify the name of a contract when the regular name is not descriptive enough (like `proxy` instead of `GnosisProtocol`)
- `logo` would allow us to show an icon identifying known contracts

**Comment by rmeissner** [comment]
I would say hosted by us

**Comment by tschubotz** [comment]
Currently, name and logo is restricted to contracts, i.e. I cannot give a known address which is not a contract a name. Will this be change later or do we need a separate ticket for this?

**Comment by Uxio0** [comment]
Maybe the naming is not the best one, but the feature is still there... We can just add addresses without ABIs, but that depends on how @jpalvarezl and @rmeissner want to query the core services from the client gateway.

Either I create another model "EOA" or something like that and we have 2 endpoints `/contracts/` and `/eoas/` or I change the model name and create a single endpoint `/known-addresses/`, with same structure but `abi: null` for EOAs

WDYT @jpalvarezl @rmeissner ?

**Comment by rmeissner** [comment]
Why can we not use https://github.com/gnosis/safe-transaction-service/blob/master/safe_transaction_service/contracts/models.py#L130 and don't link an abi?

**Comment by Uxio0** [comment]
> Edit: I know it is called "Contract" but who does this really stop us from putting other addresses there?
Nothing, that's why I said maybe I should rename the class/endpoint

> Edit 2: https://github.com/gnosis/safe-transaction-service/blob/master/safe_transaction_service/contracts/models.py#L135 is Cascade the best option here? (since Abi and Contract exists independent from each other)

Good point, it's not the best option

**Comment by tschubotz** [comment]
> Edit 3: @tschubotz just leave the `name` field empty

Leaving the name field empty is no problem. But the ABI is currently required. Hence I'm asking whether this could be made optional (+ potentially renaming the model to prevent confusion, yes. `address` or `account` could work e.g.)

![image](https://user-images.githubusercontent.com/1380529/105682132-55d43800-5ef2-11eb-87f2-35c9608ba767.png)

**Comment by Uxio0** [comment]
Shouldn't be required, that's a typo 🙃

**Comment by Uxio0** [comment]
@tschubotz This is fixed

**Comment by tschubotz** [comment]
> @tschubotz This is fixed, can you check again? 😃

Looks good, thanks! 

Feel free to close this issue or leave open for the potential renaming discussion. Your call @Uxio0

**Comment by Uxio0** [comment]
I will close if for now, and if we need a rename we can always open a new one 😉
