### ISSUE TITLE
ERC721 token not displayed

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#211]
**Describe the bug**
ERC721 token (Cryptovoxels) not displayed

**To Reproduce**
1. Open https://gnosis-safe.io/app/#/safes/0xf5A07f885B9C2BC30e3766F5727E05bCE8b2B549/transactions
2. There is an incoming transfer of 1 CVPA
3. Go to assets-> Collectibles
4. No token

**Expected behavior**
I see the token

**Additional context**
The token is visible on Opensea: https://opensea.io/accounts/0xf5A07f885B9C2BC30e3766F5727E05bCE8b2B549
It also seems to me like it's a proper ERC721 token (https://etherscan.io/address/0x79986af15539de2db9a5086382daeda917a9cf0c#code)

Etherscan labels this as ERC20 token ([Safe on Etherscan](https://etherscan.io/address/0xf5A07f885B9C2BC30e3766F5727E05bCE8b2B549)), so something fishy might be going on here. But since the backend captures it correctly for the tx list, I was wondering why it's not correct on the assets list.

**Screenshots**
![image](https://user-images.githubusercontent.com/1380529/104918731-77cf3700-5995-11eb-9e82-d3fce5c12e56.png)
![image](https://user-images.githubusercontent.com/1380529/104918769-89b0da00-5995-11eb-807b-123c71676dc8.png)

**Comment by Uxio0** [comment]
Hi, `Transfer` event is not proper for an ERC721: `event Transfer(address indexed _from, address indexed _to, uint256 _tokenId);`, `tokenId` should be indexed. That's why it's not showed

**Comment by tschubotz** [comment]
.. and I thought I double checked that 🙄 
Thanks for checking.

**Comment by Uxio0** [comment]
> .. and I thought I double checked that 🙄

No worries 😉
