### ISSUE TITLE
Add endpoint to estimate safeTxGas for a transaction

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-transaction-service#212]
Estimating the `safeTxGas` for a transaction is not straight forward as you need to decode a revert message. Providing an endpoint for this would be very helpful for the web interface and can be used by the mobile clients in the future.

Notes:
- Should this be a combined endpoint with the data decoding for creation (or should the client gateway combine these)
- Do we see a security issue here? (service returning wrong safeTxGas)
  - (Richard) I would say "no", as the user can overwrite it and we show in the interface if a tx would fail before execution

**Comment by Uxio0** [comment]
> Should this be a combined endpoint with the data decoding for creation (or should the client gateway combine these)
Not on the core services (one can be easily cached, the other doesn't)

> Do we see a security issue here? (service returning wrong safeTxGas)
No, we are already using less reliable methods
