### ISSUE TITLE
500 retrieving tx details

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#213]
**Describe the bug**
500 retrieving tx details

**To Reproduce**
1. https://safe-client-mainnet.gnosis.io/v1/safes/0x5a1Bc518E8d34979479aA9c48cc3E3c062248Fa7/transactions

Returns:
```json
{
   "id":"ethereum_0x5a1Bc518E8d34979479aA9c48cc3E3c062248Fa7_0x84091ae0da7af7dbdd821e197389a64a607dece10440a74f81aaa35367e85e13_0x23cd7809c7bfb69f",
   "timestamp":1611848039000,
   "txStatus":"SUCCESS",
   "txInfo":{
      "type":"Transfer",
      "sender":"0x993205ac41b7AD857bb99224Ef463e24FBD7AC24",
      "recipient":"0x308686553a1EAC2fE721Ac8B814De638975a276e",
      "direction":"UNKNOWN",
      "transferInfo":{
         "type":"ERC20",
         "tokenAddress":"0x6810e776880C02933D47DB1b9fc05908e5386b96",
         "tokenName":"Gnosis Token",
         "tokenSymbol":"GNO",
         "logoUri":"https://gnosis-safe-token-logos.s3.amazonaws.com/0x6810e776880C02933D47DB1b9fc05908e5386b96.png",
         "decimals":18,
         "value":"16008000000000000000"
      }
   },
   "executionInfo":null,
```

2. Check tx deteails for that id `ethereum_0x5a1Bc518E8d34979479aA9c48cc3E3c062248Fa7_0x84091ae0da7af7dbdd821e197389a64a607dece104`
3. https://safe-client-mainnet.gnosis.io/v1/transactions/ethereum_0x5a1Bc518E8d34979479aA9c48cc3E3c062248Fa7_0x84091ae0da7af7dbdd821e197389a64a607dece10440a74f81aaa35367e85e13_0x23cd7809c7bfb69f
4. error 500

![image](https://user-images.githubusercontent.com/1380529/106169139-563d2f00-618f-11eb-9a55-a7cd6f91b495.png)

**Expected behavior**

tx details load without issue

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox

**Comment by Uxio0** [comment]
> This is a core service error, this transaction should not be returned for that safe (at least not with the information it does ... looks like the wrong transfer object is attached). See
> https://safe-transaction.gnosis.io/api/v1/safes/0x5a1Bc518E8d34979479aA9c48cc3E3c062248Fa7/all-transactions/

What do you mean by `wrong transfer object `? It's an incoming ERC20 transfer triggered by other account, and it just returns the transfer related to that Safe.

**Comment by rmeissner** [comment]
It updated itself .... tss tss tss xD ... did you reindex?

As you can see in tobias comment the original transfer returned was not the correct one as it was not related. But you are correct that this issue doesn't exist anymore for this example.

**Comment by Uxio0** [comment]
I didn't reindex... Maybe it's a caching issue, I will take a look

**Comment by Uxio0** [comment]
Confirmed, it's a caching issue. It went away after flushing redis

**Comment by Uxio0** [comment]
I found the issue. Transactions are cached on the asumption that with the same `txHash` the returned object will be the same, which is not the case for transfers
