### ISSUE TITLE
Add known contracts

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#214]
# What is needed?
Please import the following known contracts and icons as discussed on Slack and mirror them to both staging and prod mainnet.

https://drive.google.com/file/d/164hLpc1hXp1vH63juYl3cSluBRoK-WjP/view?usp=sharing

Note: I also imported manually a number of contracts on staging, please mirror them to production also.

**Comment by Uxio0** [comment]
It's imported on staging
