### ISSUE TITLE
Endpoint to fetch decoded data for given tx data

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#218]
_Creating this issue on behalf of the safe-react team. @Agupane, @fernandomg_

**Is your feature request related to a problem? Please describe.**
On safe-react we have this feature coming up: Decode tx data during tx creation - https://github.com/gnosis/safe-react/issues/898

**Describe the solution you'd like**

_(Copied from https://github.com/gnosis/safe-react/issues/898#issuecomment-778315331)_

- The endpoint we need would be something like this:

POST /decodeData
```json
{
 "hexData": "0x."
}
```

The response should be like this (based on how the client gateway it's working now)

```ts
type Response = {
 txData: DecodedTransaction
}
```

The types are:
```ts
type Params = {
  name: string; 
  type: string;
  value: string;
}

type DataDecoded = {
  method: string;
  params: Params[];
}

type DecodedTransaction = {
  hexData: string; 
  dataDecoded: DataDecoded | DecodedTransaction[]; // dataDecoded will be DecodedTransaction[] for isMultiSend === true
  isMultisend: boolean;
}
```

We expect that the decodification will go for the first level, in case there are nested **multiSend** transactions it won't return `dataDecoded` value, just `hexData` so we can ask for decoded data later in case we need it

**Describe alternatives you've considered**
?

**Additional context**

**Comment by Uxio0** [comment]
@Agupane @dasanra I've reviewed this proposal. I don't get `based on how the client gateway it's working now`, as this is a new structure and not related to how the client gateway works (gateway just copies the same structure that we use in the core services).

I would say to use the same structure we currently have on the transaction service, as the work is already done and serializers and edge cases are well tested and covered. I would only change the structure if you feel there's an advantage in doing so. One example of transaction would be https://safe-transaction.mainnet.staging.gnosisdev.com/api/v1/transactions/0x68ba2b6b50886b0bb436cb8c3dd1fb598f9934f32436adafeec20cc5031c1d0a/ :

Data decoded would be:

```json
{
   "dataDecoded":{
      "method":"multiSend",
      "parameters":[
         {
            "name":"transactions",
            "type":"bytes",
            "value":"0x00ca6e3ebf4ac8c3e84bccdf5cd89aece74d69f2a700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024a694fc3a00000000000000000000000000000000000000000006fd90c06de2e7216e45f2",
            "valueDecoded":[
               {
                  "operation":0,
                  "to":"0xCa6E3EBF4Ac8c3E84BCCDF5Cd89aece74D69F2a7",
                  "value":"0",
                  "data":"0xa694fc3a00000000000000000000000000000000000000000006fd90c06de2e7216e45f2",
                  "dataDecoded":{
                     "method":"stake",
                     "parameters":[
                        {
                           "name":"amount",
                           "type":"uint256",
                           "value":"8450983834988719532557810"
                        }
                     ]
                  }
               }
            ]
         }
      ]
   }
```

If you need a hint for TypeScript you can take a look in the client gateway models https://github.com/gnosis/safe-client-gateway/blob/main/src/models/commons.rs#L14

**Comment by Uxio0** [comment]
Updated proposal

**Endpoint**

POST /api/v1/data-decoder/
```json
{
 "data": "0x."
}
```

**Response**

```ts
type Parameters = {
  name: string; 
  type: string;
  value: string;
  valueDecoded: Response  // when value can be decoded (Multisend or call to GnosisSafe `execTransaction`)
}

type Response = {
  method: string;
  parameters: Parameters[];
}
```

Decodification will go for all the levels, and clients will be able to choose what they will use. Reasoning for is that this behaviour was motivated by the expectation of optimizing both the data exchanged and the backend:
- Backend does not have any problem on decoding stuff, it's a fast process.
- Regarding saving exchanged data, if backend has to retrieve the remaining `data` not decoded data transferred would be bigger than their `dataDecoded` counterpart (as utf8 is usually smaller than solidity binary).

**Comment by Uxio0** [comment]
> What do you think @Agupane @dasanra?

After a meeting with @dasanra we agreed to go this way and modify on demand if there's any need from the frontend that we didn't think of
