### ISSUE TITLE
Add tokens icons for mainnet

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#222]
I fetched some missing token icons via token lists. Script is [here](https://github.com/tschubotz/scripts/blob/main/get_icons_token_lists/get_icons_token_lists.py) if you're interested.
Only for tokens, that the tx service knows about already.

Could you please add them to mainnet prod? 

[token_list2.zip](https://github.com/gnosis/safe-transaction-service/files/6009430/token_list2.zip)

**Comment by tschubotz** [comment]
Wait, some of them might be svgs instead of pngs actually, I just saw. Need to double check!

**Comment by tschubotz** [comment]
Alright, now jpg and svg should be properly converted to pngs. I updated the archive in the ticket description with the correct one. Let me know if this works :)

**Comment by Uxio0** [comment]
Done 😉
