### ISSUE TITLE
Owner device receives a notification for a transaction proposed/signed by itself

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#234]
**Describe the bug**
Owner device receives a notification for a transaction proposed/signed by itself

**To Reproduce**
1. Import owner 1 on mobile and connect the same owner in MM to web app
2. Create new tx as owner from step 1

**Current result**
The same owner received “your confirmation required” notification on mobile for just created by him transaction

**Expected behavior**
Same owner does not receive the “your confirmation required” notification

**Comment by Uxio0** [comment]
Webhook is processed before the confirmation is added to the transaction, so `process_webhook` should take that into consideration.

**Comment by Uxio0** [comment]
I delayed 3 seconds the notification (on staging mainnet/rinkeby) so it takes time to the backend to process all the signatures. @liliya-soroka is this still happening?

**Comment by liliya-soroka** [comment]
The issue can be closed as fixed, I can not reproduce it on staging, rinkeby now

**Comment by Uxio0** [comment]
Good to hear that, thanks @liliya-soroka !
