### ISSUE TITLE
Change registration endpoint behaviour

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#242]
# What is needed?
Every signer sent CAN be an owner of any number of Safes. If not, all the valid signers must be inserted in database and a warning about the invalid ones should be returned.

# Background
Currently every signer sent MUST be an owner of at least one Safe and a error is sent if they are not.

**Comment by Uxio0** [comment]
@gnosis/safe-android @gnosis/safe-ios 

Endpoint behaviour has been changed:
- Addresses that don't belong to any Safe will be ignored, the rest will be inserted.
- There are now 2 new fields in the return object, `ownersRegistered` and `ownersNotRegistered`, they both are a `list` (can be empty) of ethereum checksummed address.

**Comment by liliya-soroka** [comment]
I will test it on staging on Monday, as it's requires good regression for notifications + multiple owner keys

**Comment by liliya-soroka** [comment]
@Uxio0 , checked on staging . It works with non-owners
