### ISSUE TITLE
Data not decoded

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#249]
**Describe the bug**
Data not decoded

**To Reproduce**

1. [This Safe](https://gnosis-safe.io/app/#/safes/0xBc79855178842FDBA0c353494895DEEf509E26bB/transactions) interacted with a contract called [BorrowerOperations](https://etherscan.io/address/0x24179CD81c9e782A4096035f7eC97fB8B783e007#code) in tx with nonce 357.
2. I added the ABI for this yesterday to the [staging admin](https://safe-transaction.mainnet.staging.gnosisdev.com/admin/contracts/contractabi/4290/change/?_changelist_filters=q%3DBorrowerOperations)
-> Today still not decoded.

![image](https://user-images.githubusercontent.com/1380529/119104278-60c05480-ba1c-11eb-9729-ba8c64d148f5.png)

**Expected behavior**
tx data is decoded today

**Additional context**
That's the tx on the tx service: https://safe-transaction.gnosis.io/api/v1/safes/0xBc79855178842FDBA0c353494895DEEf509E26bB/multisig-transactions/?nonce=357

**Comment by Uxio0** [comment]
@tschubotz Transaction is decoded now, it was a caching issue, but I will not close this until I figure out a solution

**Comment by tschubotz** [comment]
Thanks, I can confirm that it works now. Also for all ABIs I added, except this one:

- Tx  with nonce 2097 from https://gnosis-safe.io/app/#/safes/0xEb3107117FEAd7de89Cd14D463D340A2E6917769/transactions
- Calls this contract https://etherscan.io/address/0xD3C8d372bFCd36c2B452639a7ED6ef7dbFDC56F8#code
- ABI in the backend which I added yesterday: https://safe-transaction.mainnet.staging.gnosisdev.com/admin/contracts/contractabi/3421/change/?_changelist_filters=q%3Dsystemsettings

**Comment by Uxio0** [comment]
I think you pasted the wrong ABI 😉 , I updated the ABI to be the one in the contract and now it's working https://safe-transaction.mainnet.staging.gnosisdev.com/api/v1/transactions/0x521769347b7a1aefc0fe544c6dc98304835295f4e89b7a81b2e4a2c57ec72ed8/

**Comment by tschubotz** [comment]
Thanks 🙈

**Comment by Uxio0** [comment]
https://gitlab.gnosisdev.com/devops/gnosis-prod/-/issues/280
