### ISSUE TITLE
Auto index ABIs

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#265]
# What is needed?
ABIs are added manually to the database, we would like them to be indexed from Etherscan/Sourcify.

**Comment by tschubotz** [comment]
For which networks will this work? Mainnet and Rinkeby? How about xdai?

Are the ABIs shared across networks?

**Comment by Uxio0** [comment]
- Currently every network is supported via Sourcify. Etherscan supports Mainnet, Rinkeby and Binance and Blockscout supports Xdai, Matic, Mumbai, EWC and Volta.
- More networks should be very easy to add as long as there's an etherscan or blockscout running instance, but must be added manually.
- Abi sharing across networks is a more complex thing and will be addressed in #277

**Comment by tschubotz** [comment]
>     * Etherscan supports Mainnet, Rinkeby and Binance

Etherscan also supports Polygon (https://polygonscan.com/). Did you add it already or do you want me to create a separate issue for this?

**Comment by Uxio0** [comment]
> > ```
> > * Etherscan supports Mainnet, Rinkeby and Binance
> > ```
> 
> Etherscan also supports Polygon (https://polygonscan.com/). Did you add it already or do you want me to create a separate issue for this?

I was not aware of it, I just added it and test it
