### ISSUE TITLE
Add ABI for EulerBeats contracts

### ISSUE THREAD

**Issue by jonson** [gnosis/safe-transaction-service#270]
We use a safe to manage our contracts (:heart: the webapp) and would love to get a few methods indexed.  Linking the etherscan verified contracts here:

EulerBeats:
https://etherscan.io/address/0x8754F54074400CE745a7CEddC928FB1b7E985eD6#code

EulerBeatsV2:
https://etherscan.io/address/0xa98771a46Dcb34B34cDAD5355718F8a97C8E603e#code

PrintingPress:
https://etherscan.io/address/0x8Cac485c30641ece09dBeB2b5245E24dE4830F27#code

EulerBeatsPairStaking:
https://etherscan.io/address/0xFA21807EDE5486c83d665812525ff44C5B72F3ED#code

Thanks!

**Comment by Uxio0** [comment]
Contracts have been added and will be tomorrow morning in production
