### ISSUE TITLE
Endpoint for retrieving connected Safe(s) for owner address

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#28]
- We are planning on improving the recovery flow (safe#180).
- As part this, we would like to remove the step where a user has to enter the Safe address.
- Therefore we need an endpoint where the apps can retrieve Safe addresses for a given owner address.

**Comment by Uxio0** [comment]
@tschubotz, this is my proposal for the API:

# Endpoint for retrieving connected Safes for an owner

## Url
`POST` /v1/safes/recovery/

## Request POST data
Endpoint expects a `json` with the owner/s to be queried. Owner/s must be checksummed, if not, response will be `422 Unprocessable Entity`
```json
{
  "owners": ["safe_owner_1", "safe_owner_2"]
}
```

## Response data
Endpoint will return a list of checksummed Safe addresses the user is *currently* an owner of (not Safes that the user has *previously* been an owner of). HTTP Status Code will be `200 OK` if at least one Safe is found and `404 Not Found` if no Safe is found for that owner.
```json
["safe_address_1", "safe_address_2", "..."]
```

**Comment by Uxio0** [comment]
My new proposal

# Endpoint for retrieving connected Safes for an owner

## Url
`GET` /v1/owners/<checksummed-address>/

## Response data
Endpoint will return a list of checksummed Safe addresses the user is *currently* an owner of (not Safes that the user has *previously* been an owner of). HTTP Status Code will be `200 OK` if at least one Safe is found and `404 Not Found` if no Safe is found for that owner.
```json
{
  "safes": ["safe_address_1", "safe_address_2", "..."]
}
```
