### ISSUE TITLE
Add proper support for EIP1559

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#307]
# Background
- https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md

Basic support was added on e4f452e9eaefc2f628a8556691babaa815b5c4e7

**Comment by rmeissner** [comment]
More links:
- https://twitter.com/TimBeiko/status/1413532890747441158?s=20
- https://github.com/ethereum/eth1.0-specs/pull/251

**Comment by Uxio0** [comment]
This issue became relevant for a possible integration with another services. I decided to implement it as the long it takes we have to reindex more transactions
