### ISSUE TITLE
DODO token not showing up in BSC token list UI

### ISSUE THREAD

**Issue by ennisjo** [gnosis/safe-transaction-service#315]
**Describe the bug**
DODO token does not display in the https://bsc.gnosis-safe.io/ token list UI even though it is compliant with the BEP20 standard. 

**To Reproduce**
1. Click on https://bsc.gnosis-safe.io/app/#/safes/0x5abbF2bbC6E5520e3d274007546a67B6B333564C/balances and observe the token list UI.
2. Cross reference what is displayed in the UI with BSCscan - https://bscscan.com/address/0x67ee3cb086f8a16f34bee3ca72fad36f7db929e2

**Expected behavior**
Token appears in the user's UI, based on latest BSCscan data.

**Comment by Uxio0** [comment]
Every token is showing up now
