### ISSUE TITLE
Newly added tokens are not reflecting in Polygon UI list and transactions log

### ISSUE THREAD

**Issue by ennisjo** [gnosis/safe-transaction-service#316]
**Describe the bug**
Newly added tokens and transactions are not updating on the token list and transactions log respectively. Taking place on https://polygon.gnosis-safe.io/app. Transaction log also isn't updating. https://polygon.gnosis-safe.io/app/#/safes/0xf61B1F57A00B4379Ceb6FF074034FDb795f69C3c/balances.

**To Reproduce**

1. Load up Safe on https://polygon.gnosis-safe.io/app/#/safes/0xf61B1F57A00B4379Ceb6FF074034FDb795f69C3c/balances
2. Load up corresponding address on polyscan - https://polygonscan.com/address/0xf61B1F57A00B4379Ceb6FF074034FDb795f69C3c
3. Click on ERC20 token drop down list on Polyscan
4. Observe latest Safe tx's taken place on Polyscan

**Expected behavior**
ERC20 balance and tx's on Polyscan should match on https://polygon.gnosis-safe.io/app/#/safes/0xf61B1F57A00B4379Ceb6FF074034FDb795f69C3c/balances and https://polygon.gnosis-safe.io/app/#/safes/0xf61B1F57A00B4379Ceb6FF074034FDb795f69C3c/transactions

**Additional context**
UI hasn't updated for 17+ hours as of writing

**Comment by Uxio0** [comment]
Polygon is updated now!
