### ISSUE TITLE
Safes cannot be loaded on Polygon - https://polygon.gnosis-safe.io/

### ISSUE THREAD

**Issue by ennisjo** [gnosis/safe-transaction-service#317]
**Describe the bug**
Several Safes cannot be loaded in the UI through https://safe-client.polygon.gnosis.io/v1/safes/ and https://polygon.gnosis-safe.io/app/#/safes/ADDRESS/balances

**To Reproduce**
1. Paste Safe address into https://polygon.gnosis-safe.io/app/#/safes/ADDRESS/balances
2. Wait for Safe to load in the web UI 
3. Open Network tab in Dev Tools

**Expected behavior**
Safe is loaded successfully and not hanging on the loading screen

**Additional context**
Tries to access https://safe-client.polygon.gnosis.io/v1/safes/ADDRESS/ which internally tries to fetch the info from https://safe-transaction.polygon.gnosis.io/api/v1/safes/ADDRESS/ which returns a 404, i.e. Safe not found.

ADDRESS can be found at https://gnosisinc.slack.com/archives/CQB729LLF/p1627486565164800?thread_ts=1627486545.164500&cid=CQB729LLF

**Comment by Uxio0** [comment]
This issue has been fixed, please feel free to reopen if there's a problem again
