### ISSUE TITLE
safeTxGas estimation for smart contract upgrade is failing

### ISSUE THREAD

**Issue by dasanra** [gnosis/safe-transaction-service#318]
**Describe the bug**
When trying to get an estimation of safeTxGas for a smart contract upgrade it gets an error.

**To Reproduce**
1. Do POST on https://safe-transaction.rinkeby.staging.gnosisdev.com/api/v1/safes/0x8e37AAcCd416d08D09e52659E13ceB05280cA431/multisig-transactions/estimations/

example data:
`{
"data": "0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000f2008e37aaccd416d08d09e52659e13ceb05280ca431000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000247de7edef0000000000000000000000003e5c63644e683549055b9be8653de26e0b4cd36e008e37aaccd416d08d09e52659e13ceb05280ca43100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024f08a0323000000000000000000000000f48f2b2d2a534e402487b3ee7c18c33aec0fe5e40000000000000000000000000000",
"operation": 1,
"to": "0x40A2aCCbd92BCA938b02010E17A5b8929b49130D",
"value": "0"
}`

**Expected behavior**
I would expect to get a correct gas estimation

**Comment by rmeissner** [comment]
Operation should be `1`

**Comment by Uxio0** [comment]
Just for reference, actual example of multisend update: https://safe-transaction.rinkeby.gnosis.io/api/v1/multisig-transactions/0x22dd97d06df459b5a443c788c9f35d78608b8f8988404a4bc3ee37e22393c653/

**Comment by dasanra** [comment]
@rmeissner yes sorry about that, we were setting wrong operation and wrong to for the estimation and the correct values for sending it. Thank you for pointing that!

@Uxio0 thank you for your time checking!
