### ISSUE TITLE
known contract logos don't show up on BSC/Polygon when accessed via admin

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#323]
**Describe the bug**
known contract logos don't show up on BSC/Polygon

**To Reproduce**
(Example is for bsc but the same thing can be reproduced on the polygon admin)

1. Open https://safe-transaction.bsc.gnosis.io//admin/contracts/contract/0x3E5c63644E683549055b9Be8653de26E0B4CD36E/change/?_changelist_filters=q%3D0x3E5c63644E683549055b9Be8653de26E0B4CD36E
2. Click the icon url (https://safe-transaction.bsc.gnosis.io/media/contracts/logos/0x3E5c63644E683549055b9Be8653de26E0B4CD36E.png)
-> not found

**Expected behavior**
Icon shows up like it does e.g. on mainnet ([admin url](https://safe-transaction.mainnet.staging.gnosisdev.com//admin/contracts/contract/0x3E5c63644E683549055b9Be8653de26E0B4CD36E/change/?_changelist_filters=q%3D0x3E5c63644E683549055b9Be8653de26E0B4CD36E), [logo url](https://safe-transaction-assets.staging.gnosisdev.com/contracts/logos/0x3E5c63644E683549055b9Be8653de26E0B4CD36E.png))

**Comment by liliya-soroka** [comment]
There are also no logos for:
1. tokens on ASSETS list ( BSC, did not check other L2 networks)
https://safe-transaction.bsc.gnosis.io/
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "type": "ERC20",
      "address": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
      "name": "Wrapped BNB",
      "symbol": "WBNB",
      "decimals": 18,
      "logoUri": "https://gnosis-safe-token-logos.s3.amazonaws.com/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c.png"
    }
  ]
}

**Comment by fmrsabino** [comment]
> There are also no logos for:
> 
> 1. tokens on ASSETS list ( BSC, did not check other L2 networks)
>    https://safe-transaction.bsc.gnosis.io/

There are two types of logos:
- Known addresses/contracts logos – stored under https://safe-transaction-assets.gnosis-safe.io
- Tokens – stored under https://gnosis-safe-token-logos.s3.amazonaws.com/

The original issue seems to be related with the first one where the S3 storage is not set so the url is an invalid one.

For the one that you reported it seems that the icon is simple missing from `https://gnosis-safe-token-logos.s3.amazonaws.com/`. This can probably be solved just by using the admin interface.

**Comment by fmrsabino** [comment]
Issue fixed.

https://safe-transaction.bsc.gnosis.io/api/v1/contracts/0x3E5c63644E683549055b9Be8653de26E0B4CD36E/ now returns the correct url for the logo: https://safe-transaction-assets.gnosis-safe.io/contracts/logos/0x3E5c63644E683549055b9Be8653de26E0B4CD36E.png

@liliya-soroka regarding your issue we can have a look at it but it's a different endpoint than the one posted by Tobias.
