### ISSUE TITLE
docker-compose.dev.yml uses undefined volume

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-transaction-service#326]
**Describe the bug**
The web image on `docker-compose.dev.yml` references a non existing volume: `nginx-shared`. (This volume is declared on `docker-compose.yml`)

**To Reproduce**
1. `docker compose -f docker-compose.dev.yml up`

```
service "web" refers to undefined volume nginx-shared: invalid compose project
```

**Expected behavior**
`docker-compose.dev.yml` launches all the containers without issues.

**Comment by Uxio0** [comment]
That file is intended to inherit from `docker-compose.yml`, so it should be documented 😉 . Thanks for noticing!

Command should be `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up`

**Comment by fmrsabino** [comment]
I see. Thanks @Uxio0! Feel free to close this ticket then!
