### ISSUE TITLE
ERC721 assets not displaying in Safe BSC UI

### ISSUE THREAD

**Issue by ennisjo** [gnosis/safe-transaction-service#333]
**Describe the bug**
NFT images in this safe are not displaying - https://bsc.gnosis-safe.io/app/#/safes/0x4E8999970D1DD97cd52832C6238a3a9E310890c7/balances/collectibles

**To Reproduce**
1. Open Safe on https://bsc.gnosis-safe.io/app/#/safes/0x4E8999970D1DD97cd52832C6238a3a9E310890c7/balances/collectibles
2. View collectibles section

**Expected behavior**
The NFT images should be displayed since it's believed to be 721-compliant.

**Additional context**
They are using this structure in their API endpoint: https://eips.ethereum.org/EIPS/eip-721 (title ERC721 Metadata JSON Schema)

Example: https://pcats.pixuverse.com/tokens/4

**Comment by rmeissner** [comment]
The json returned by https://pcats.pixuverse.com/tokens/4 does not follow EIP-721. 

The schema mentioned in the EIP is:
```json
{
    "title": "Asset Metadata",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "Identifies the asset to which this NFT represents"
        },
        "description": {
            "type": "string",
            "description": "Describes the asset to which this NFT represents"
        },
        "image": {
            "type": "string",
            "description": "A URI pointing to a resource with mime type image/* representing the asset to which this NFT represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive."
        }
    }
}
```

To test your returned json against it you can use any json validator (e.g. https://jschon.dev/).

Note: In the EIP-721 none of the properties are `required`. To make sure that your json is valid I would recommend to add a requirement for the properties you always want to return and check it with the adjusted schema. For example:

Schema for a NFT that always has a name, description and image:

```json
{
    "title": "Asset Metadata",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "Identifies the asset to which this NFT represents"
        },
        "description": {
            "type": "string",
            "description": "Describes the asset to which this NFT represents"
        },
        "image": {
            "type": "string",
            "description": "A URI pointing to a resource with mime type image/* representing the asset to which this NFT represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive."
        }
    },
  "required": [
    "name",
    "description",
    "image"
  ]
}
```

Your example json:
```json
{
  "title": "PIXU Cat Assets Metadata",
  "properties": {
    "name": "PixuCat #4 - 0x0100100230",
    "description": "The official Pixuverse Cat. More info: https://www.pixuverse.com and https://twitter.com/pixuverse.",
    "image": "https://pcats.pixuverse.com/token-images/100100230.png"
  }
}
```

Result from `https://jschon.dev/`:
![image](https://user-images.githubusercontent.com/2896048/129691738-ba329a4c-971d-486a-8806-d09a168b589b.png)

Therefore I will close this issue for now
