### ISSUE TITLE
Add ABI for Beta Finance contracts

### ISSUE THREAD

**Issue by allenjlee** [gnosis/safe-transaction-service#375]
Please decode all methods of the Beta Finance contracts listed below, thank you.

Details:
ProxyAdmin: https://etherscan.io/address/0x0673418735981c0b54ecb483076f1de0372e5171#code

BetaBank: https://etherscan.io/address/0x972a785b390d05123497169a04c72de652493be1#code

BetaOracle: https://etherscan.io/address/0x39a31eff10631ef94d2f34b7d72ca01b0f0f84de#code

BetaConfig: https://etherscan.io/address/0x59334e2693168c3f8c9e0fcbe029dab9daf6b9c5#code

BetaRunnerLending: https://etherscan.io/address/0x068af1ec336344cd122b9811ef90d2384519005f#code

BetaRunnerUniswapV2: https://etherscan.io/address/0x9136dfac5435cd0bc627b9400415a19690134a63#code

BetaRunnerUniswapV3: https://etherscan.io/address/0x06f12b17d97ef27152b68cba208e3415ea65369b#code

**Comment by Uxio0** [comment]
ABIs have been added
