### ISSUE TITLE
Add flags to endpoint to only return trusted or non spamming token

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-transaction-service#41]
Service is returning balance for every ERC20 token detected for a Safe address, even for the scammy tokens.

- Add flags `spam` and `trusted` flag to `tokens` endpoint to filter with a `boolean` by these values.
- Add `spam` field to token model to mark a token a spam token.
- Add access for product managers to have the possibilty to mark tokens as spam tokens.

Depends on #37

**Comment by Uxio0** [comment]
@lukasschor This is something @rmeissner discussed with me the other day, I think it could make interface cleaner. In my case I have already been sent some scam tokens to my personal account and they show on the interface. I can make it optional as a parameter too so frontend decide if they one a whitelisted list or not

**Comment by lukasschor** [comment]
Yes I think that makes sense, but wouldn't consider it high-priority at this point.
