### ISSUE TITLE
cDAI balance not returned correctly.

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#43]
Not sure if this is the right place, but here's a bug/issue:

- https://etherscan.io/address/0xFB1d445c27A860bb6330453Bf08254198F3E0E31 has a cDAI balance of >0

- https://safe-transaction.mainnet.staging.gnosisdev.com/api/v1/safes/0xFB1d445c27A860bb6330453Bf08254198F3E0E31/balances/?limit=300 doesn't return cDAI

**Comment by Uxio0** [comment]
@tschubotz Service has indexed cSAI and cDAI movements for that address, but current balance for both is 0, so it's not showing in the service

**Comment by tschubotz** [comment]
🤦‍♂  I was confused
