### ISSUE TITLE
Add support for webhooks

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-transaction-service#44]
### What
It would be nice to be able to define webhooks that should be triggered when new confirmation, transactions, etc are added.

### Why
Our transactions service handles quite some useful information and it would be nice if it is possible to build services around this. Webhooks would allow other services to better interact with the transactions service.

### How
Add a webhooks model, so that we can add webhooks via the admin interface.
The webhooks should be triggered each time any of the following actions occur:
- When a new pending outgoing transaction is added to the database
- When a new confirmation is added to the database
- When a new executed outgoing transaction is added to the database
- When a new incoming transaction is added to the database
- TBD

**Comment by rmeissner** [comment]
Define payload that is send with the webook

**Comment by Uxio0** [comment]
> Define payload that is send with the webook

I guess it should be different depending on the action:
- Pending outgoing transaction: safeTxHash, so you can query the service
- Confirmation: owner and safeTxHash. With safeTxHash should be alone, as you can query the service.
- New executed outgoing tx: safeTxHash
- New incoming tx: txHash, value, tokenAddress

**Comment by rmeissner** [comment]
I would add the safe address to all payloads :)
