### ISSUE TITLE
LP Token dollar values are not supported

### ISSUE THREAD

**Issue by Rafanator** [gnosis/safe-transaction-service#449]
# What is needed?
LP Token dollar values are not supported. 

# Background
Gnosis Safe doesn't show the dollar value of LP tokens including Uniswap, Sushiswap, Curve, and Balanacer. It would improve user experience quite a lot of this was the case, as many treasuries and large holders LP in these DEXs. 

# Related issues
https://github.com/gnosis/safe-react/issues/2523

cc/ @mikheevm

**Comment by mikheevm** [comment]
I tested the [LP token](https://etherscan.io/address/0x8a649274e4d777ffc6851f13d23a86bbfa2f2fbf) in the issue, and the calculation at the service level worked just fine. I couldn't find any Safes with this token to test it more thoroughly.

**Comment by Uxio0** [comment]
Thanks @mikheevm !
