### ISSUE TITLE
Add state information for executed transactions

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-transaction-service#46]
It would be nice to display some information about a transaction once it has been executed:

- Confirmation required on time of execution.
- Confirmation used on-chain to execute the transaction.
- Fees paid to execute the transaction and receiver of the fees (if applicable)
- ...

**Comment by Uxio0** [comment]
Detected transactions in the payload? (Changing owners, threshold, updating master copy, etc.)

**Comment by rmeissner** [comment]
maybe the method signature (basically what you get from https://www.4byte.directory/)
