### ISSUE TITLE
Add ABI for Cobo Safe Module

### ISSUE THREAD

**Issue by xiaotiancobo** [gnosis/safe-transaction-service#463]
Transaction from Cobo Safe Module cannot be decoded. Please decode the methods from Cobo Safe Module listed below, thank you.
[abi.json.zip](https://github.com/gnosis/safe-transaction-service/files/7466118/abi.json.zip)
.

**Comment by Uxio0** [comment]
Hi, if you verify the module on Sourcify/etherscan it will appear. Also address of the contract should be provided
