### ISSUE TITLE
Add ABIs for CoboSafe

### ISSUE THREAD

**Issue by rex-cobo** [gnosis/safe-transaction-service#474]
Please decode all methods of Cobo safe module

Contract Address: https://rinkeby.etherscan.io/address/0x2563776361bd6334ce4eb1f9edc71ca81a444f54#code

Many Thanks

**Comment by Uxio0** [comment]
Is that module only on rinkeby or also in mainnet?

**Comment by rex-cobo** [comment]
it's only on rinkeby right now, but will be deployed on mainnet after tested thoroughly.

**Comment by Uxio0** [comment]
Ok! I'm adding it to rinkeby. So for next time, as long as you start using it after it's on Etherscan/sourcify it will be picked by the service

**Comment by Uxio0** [comment]
Indeed, I've just checked and the ABI is already in our service 😉

**Comment by rex-cobo** [comment]
Thanks a lot!!
