### ISSUE TITLE
Unable to save tx history and therefore the history tab is empty for contracts ver.1.2

### ISSUE THREAD

**Issue by denGitHub** [gnosis/safe-transaction-service#489]
Unable to save tx history and therefore the history tab is empty.
Safe contracts ver. - 1.2 
The other stack: transactions service, config service and client gateway version - latest
The error:
```
transaction-service-worker_1     | 2021-11-15 12:47:48,628 [INFO] [8e4b5cc9/index_safe_events_task] Problem inserting internal_tx: duplicate key value violates unique constraint "history_internaltx_ethereum_tx_id_trace_address_c7c2fa9c_uniq"
transaction-service-worker_1     | DETAIL:  Key (ethereum_tx_id, trace_address)=(a0e680c9f06e7a60be1fcea44376dfc333a6afdce03b32a1e9ee23e4ad0cabc0, 0) already exists.
```

We set this variable ETH_L2_NETWORK=1

Though it works fine for contracts ver -  1.3

**Comment by Uxio0** [comment]
This is not an issue. Trace was already inserted, so it's ignored, but we should improve the logging message.

1.2 contracts are not supported in L2 mode (as there is not a L2 version of the contracts), so it's expected that they appear in the indexer
