### ISSUE TITLE
Event tracking from contracts

### ISSUE THREAD

**Issue by InoMurko** [gnosis/safe-transaction-service#497]
This isn't a bug report, but a question on how to run this service.
I've bumped requirements.txt to use gnosis-py https://github.com/gnosis/gnosis-py/commits/v3.7.1a0, which has our chain id in it.
I think my `.env` is set correctly.
I added to MASTER_COPIES
```
EthereumNetwork.BOBA_RINKEBY: [
        ("0xE84AAb853C4FBaafd3eD795F67494d4Da1539492", 7756, "1.3.0+L2"),
        ("0x47b45765ee4e270dE60852295bB0Dd105E1A4Df0", 7757, "1.3.0"),
    ],
```
in setup_service.py
https://blockexplorer.rinkeby.boba.network/address/0xE84AAb853C4FBaafd3eD795F67494d4Da1539492/transactions
https://blockexplorer.rinkeby.boba.network/address/0x47b45765ee4e270dE60852295bB0Dd105E1A4Df0/transactions

PROXY_FACTORIES
```
EthereumNetwork.BOBA_RINKEBY: [
        ("0x172e17a6B3960940E3678f3CECb6288647e47877", 7749),  # v1.3.0
    ],
```
https://blockexplorer.rinkeby.boba.network/address/0x172e17a6B3960940E3678f3CECb6288647e47877/transactions

But I don't see events being consumed by the service... and I've lost ideas how to debug this. Hints? 

Thank you!

**Comment by Uxio0** [comment]
Hi, can you go to the django admin and see if there's something under `Master copies`? https://github.com/gnosis/safe-transaction-service#use-admin-interface For next support questions please go to our discord: https://discord.gg/gk53hdhZ
