### ISSUE TITLE
Attempting to call `/contract` endpoint from swagger freezes the browser

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-transaction-service#512]
**Describe the bug**
Swagger page freezes when requesting the `/contracts` endpoint.

**To Reproduce**
1. Open swagger for prod mainnet: https://safe-transaction.gnosis.io/
2. Go to `/contracts` endpoint and use `Try it out` and then `Execute`

**Expected behavior**
A paged list of the first 100 entries are returned.

**Additional context**
The URL directly in the browser appears to work fine: https://safe-transaction.gnosis.io/api/v1/contracts/

**Comment by Uxio0** [comment]
I cannot reproduce @jpalvarezl . Is someone else experiencing this @gnosis/safe-services ?

**Comment by jpalvarezl** [comment]
It seems to be only a UI freeze. I tried out in Chrome and had no issues. The spinner goes on. Firefox it freezes but it eventually returns.
