### ISSUE TITLE
API Docs link broken (GH Readme) - Where are the API docs?

### ISSUE THREAD

**Issue by lgrapenthin** [gnosis/safe-transaction-service#514]
**Describe the bug**

**To Reproduce**
1. Do POST on '...'
2. Then GET on '....'

**Expected behavior**

**Additional context**

**Comment by Uxio0** [comment]
We are restructuring the API docs. Currently our docs are on https://docs.gnosis-safe.io/backend/service-architecture

Also, you can check the swagger: https://safe-transaction.gnosis.io/
