### ISSUE TITLE
Add ABIs for CoboSafe on mainnet

### ISSUE THREAD

**Issue by xiaotiancobo** [gnosis/safe-transaction-service#525]
Cobo Safe Module has launched on mainnet: https://etherscan.io/address/0x09bd0ad84c44abd7b36c7f7bfff90776b9c42ae6
Please decode all the methods in the contract. Thank you!

**Comment by Uxio0** [comment]
If it's verified on Sourcify and etherscan it will be picked by the service 😉

**Comment by xiaotiancobo** [comment]
Thanks!
