### ISSUE TITLE
Show incoming module interactions

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-transaction-service#53]
Currently we only show incoming value transfers (e.g. ERC20 and ETH). Therefore the user currently doesn't see if a module performs a transaction via a Safe (call to `execTransactionFromModule` or `execTransactionFromModuleReturnData`).

We should expose this somehow (TBD how)

**Comment by Uxio0** [comment]
I implemented a basic test version on https://github.com/gnosis/safe-transaction-service/commit/a0c980bc7c94291c20448c3c3f194886fc8a9217
