### ISSUE TITLE
Analyze authentication alternatives for the admin interface (2FA, SSO...)

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-transaction-service#534]
# What is needed?
We should enforce 2fa for all accounts that can use the admin interface.

**Comment by Uxio0** [comment]
Should we enforce `2FA` for every admin interface or only for some networks? Then I would make it configurable

**Comment by Uxio0** [comment]
Maybe we can extend this issue and think on using a `SSO`, as we currently have a lot of service instances, with a service like `Authelia` or `Google Sign in`

**Comment by Uxio0** [comment]
We are using internally https://github.com/buzzfeed/sso . I'm analyzing if it will meet our requirements

**Comment by Uxio0** [comment]
https://github.com/buzzfeed/sso works flawlessly integrated with google accounts
