### ISSUE TITLE
`SignMessageLib` is not trusted for delegatecall opcode

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-transaction-service#538]
**Describe the bug**
Currently `SignMessageLib` contract that is used for on-chain message signing isn't in delegatecall allowlist and the UI shows a warning.

We need to add the contract to list of trusted addresses:
- old version: https://github.com/gnosis/safe-deployments/blob/e9041df9339c5cbe791a450abd6a2595619c2735/src/assets/v1.3.0/sign_message_lib.json
- recent version: https://github.com/gnosis/safe-deployments/blob/main/src/assets/v1.3.0/sign_message_lib.json

**To Reproduce**
https://gnosis-safe.io/app/rin:0xEAa3b5dB83b5737C085e4DA2f5f45199e3ac1382/transactions/queue

**Expected behavior**
NO warning is shown

## Requirements

- [x] use the Safe logo 
- [x] use "Gnosis Safe: Sign Message Library" as name 
- [ ] add Etherscan tag (@johannesmoormann)

**Comment by rmeissner** [comment]
Following information need to be decided on:
- Name that should be displayed
- Logo that should be used
  - This should be the Safe logo, used for other Safe related contracts

**Comment by rmeissner** [comment]
Also it would be good to get these verified on Etherescan

**Comment by mikheevm** [comment]
> Also it would be good to get these verified on Etherescan

They seem to be verified. Which network are they not verified?

**Comment by mikheevm** [comment]
> * Name that should be displayed

SignMessageLib? 😛

**Comment by rmeissner** [comment]
> They seem to be verified. 

I meant labeling them on Etherscan, not code verification

> SignMessageLib?

This is not in line with our other names. @johannesmoormann will coordinate

**Comment by johannesmoormann** [comment]
regarding the name tags I will speak to @lukasschor. it would be good to know whether there are more contracts that we should add, as I currently only have a list "List of known contracts (wip)" where SignMessageLib is not mentioned as an overview. looking at our contract names I would suggest something like: "Gnosis Safe: Sign Message" or "Gnosis Safe: Sign Message Library"

**Comment by Uxio0** [comment]
> use the Safe logo
> use "Gnosis Safe: Sign Message Library" as name

**Comment by johannesmoormann** [comment]
@liliya-soroka reopened for testing to pass

**Comment by liliya-soroka** [comment]
@Uxio0 , was it added for all networks and is it available on both staging and prod  or only prod?
Seems that I have access only to the staging , rinkeby, so I can not check logo and name on other networks

**Comment by liliya-soroka** [comment]
No tag for the new contract on etherscan - https://etherscan.io/address/0xA65387F16B013cf2Af4605Ad8aA5ec25a2cbA3a2

**Comment by Uxio0** [comment]
Oh no, only to `mainnet`. As every network is affected, I will write a database migration then instead of doing it manually

**Comment by johannesmoormann** [comment]
> No tag for the new contract on etherscan - https://etherscan.io/address/0xA65387F16B013cf2Af4605Ad8aA5ec25a2cbA3a2

tagging is an asynchronous process that has to be done by Etherscan team and is not required to solve the issue.

**Comment by Uxio0** [comment]
@liliya-soroka It should be already available on staging and production (every network)
