### ISSUE TITLE
safe-transaction-service support geth EVM

### ISSUE THREAD

**Issue by hanhbd1** [gnosis/safe-transaction-service#563]
# What is needed?
I tried to deploy gnosis-safe into private chain that based on geth EVM
But safe-transaction-service can't indexing anything in worker due to `trace` module not support in geth. 
What can I do on this case? 

Thank you.

**Comment by Uxio0** [comment]
Hi,

You have 2 options:
- Use OpenEthereum if your network supports it
- Use L2 Safe (with events) so tracing is not required. That's what we do for Polygon, Avalanche, Arbitrum...

There's a configuration example on https://github.com/gnosis/safe-transaction-service/blob/master/.env.tracing.sample
