### ISSUE TITLE
Hexformat not decoded

### ISSUE THREAD

**Issue by shredding** [gnosis/safe-transaction-service#566]
I'm opening a ticket as suggest [here](https://help.gnosis-safe.io/en/articles/4971390-submit-an-abi).

I still see things hex encoded, even though the ABI is [uploaded](https://rinkeby.etherscan.io/address/0x610809eAf0365BE017E22c6557b051A815046599).

![image](https://user-images.githubusercontent.com/930136/146555378-050cfb22-5a8b-4f45-b741-86b70f4cfc19.png)

It works for e.g. [this](https://rinkeby.etherscan.io/address/0xA760Ffd21D78d5a1976E85D2433aafa54dACB5Df) contract, that I uploaded in the very same way:

![image](https://user-images.githubusercontent.com/930136/146555544-49fd55f5-41c4-4765-8cad-72ed39dbe4b1.png)

**Comment by Uxio0** [comment]
ABI is on our Rinkeby database, sometimes it takes a little longer to index new contracts
