### ISSUE TITLE
Add ABI for accumMerkle contract

### ISSUE THREAD

**Issue by nkitlabs** [gnosis/safe-transaction-service#574]
Hi, could you please help decode all methods of our accumMerkle contract? ABI is provided in attached file
[accumMerkleAbi.json.zip](https://github.com/gnosis/safe-transaction-service/files/7751415/accumMerkleAbi.json.zip)
 
Thank you,

**Comment by Uxio0** [comment]
Hi, as long as your contracts are verified on Etherscan or Sourcify (better Sourcify) our service will index the ABI automatically

**Comment by nkitlabs** [comment]
this one is on avax though and could not verify contract right now. Could you please help add it?

One more thing, we deploy multisend on avalanche could you please help decode our multisend contract (0xe4Eb988bDACA6b2a6Ba383a14Bdd15dAD2720094)? (or if you have your multisend contract please let me know which contract address we should use in avax)

**Comment by Uxio0** [comment]
Sorry, we don't add not verified contracts, please verify it first

**Comment by rmeissner** [comment]
Multisend on Avalanche can be found here: https://github.com/gnosis/safe-deployments/blob/main/src/assets/v1.3.0/multi_send.json#L26
