### ISSUE TITLE
Add ABI for AB contracts

### ISSUE THREAD

**Issue by nkitlabs** [gnosis/safe-transaction-service#592]
Please decode all methods of the following contract on Avalanche.

https://snowtrace.io/address/0x01804eF6B9b193b23b9431AfE1c52803CA6525D5#code

also we deploy multisend contract on avalanche as well, could you please help decode multisend contract as well? https://snowtrace.io/address/0xe4Eb988bDACA6b2a6Ba383a14Bdd15dAD2720094#code 

Thank you

**Comment by rmeissner** [comment]
Regarding multisend: Please use the already existing multisend instances. We will not decode any other multisend instances. https://github.com/gnosis/safe-deployments/blob/main/src/assets/v1.3.0/multi_send.json#L26

We will verify the source code on snowtrace soon too. But you can already compare the bytecode to the mainnet bytecode as they should be 1 to 1 the same

**Comment by Uxio0** [comment]
Contract ABI has been added
