### ISSUE TITLE
Transaction data is still decoded even if sent to an EOA account

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-transaction-service#600]
**Describe the bug**
If you encode transaction data for a function we know (approve, transfer, safeTransferFrom, etc.) and send it to an EOA address, we still decode the transaction data

**To Reproduce**
1. Post a transaction to the backend with the ERC20 transfer function as tx data and EOA as a recipient
2. Then make a GET request for the safeTxHash

**Expected behavior**
Open for discussion, but maybe don't decode such transactions

**Environment (please complete the following information):**
 - Staging or production? production
 - Which chain? the user reported on polygon, but I think it applies to all chains 
 
 For example tx please message me privately

**Comment by rmeissner** [comment]
This is currently expected behavior. Checking if there is a contract at a specific address before decoding adds an additional overhead. Also even if there is not contracts the decoded data is technically bot wrongly decoded. Therefore we decided to keep it as is.
Note: we discussed this as part of the malicious multisend decoding.

**Comment by mikheevm** [comment]
Should we add a warning on the client-side instead, maybe?

**Comment by rmeissner** [comment]
In what flow would this occur, when the user did not manually trigger this?

**Comment by mikheevm** [comment]
The user who reported this created such a transaction with tx builder, which makes me think we could also improve it on tx builder level (makes sense given we expect to move the contract interactions there).

I think it could be a minor feature that could potentially save money for some users

**Comment by rmeissner** [comment]
Sure, might make sense there. But this means the user manually added the abi (as it would not auto load this abi for an address). This is a quite advanced action. But the transaction builder will be reworked anyways, so to might make sense to consider it as part of this.
