### ISSUE TITLE
Wrong order of transactions on Rinkeby Staging

### ISSUE THREAD

**Issue by francovenica** [gnosis/safe-transaction-service#603]
## Description
Out of order nonce when the client gateway switch is OFF.

## Environment
 - Browser: chrome
 - Wallet: MetaMask
 - Environment:
 https://safe-team.dev.gnosisdev.com/app/rin:0x219a1a38FB8e57d9b2253b78f9fE1E27E595426c/balances

https://safe-client.staging.gnosisdev.com/v1/chains/4/safes/0x219a1a38FB8e57d9b2253b78f9fE1E27E595426c/transactions/history

https://safe-client.gnosis.io/v1/chains/4/safes/0x219a1a38FB8e57d9b2253b78f9fE1E27E595426c/transactions/history?%3Ccursor%3E&%3Ctimezone_offset%3E&%3Ctrusted%3E

## Steps to reproduce
Go to the safe in the description
Switch the CGW on/off and see the tx in the history, check the order of the nonces

## Expected result
The tx should always be in the correct nonce order (higher nonce at the top)

## Obtained result
The nonces are out of order

## Screenshots
![01-03-2022_x(3855)](https://user-images.githubusercontent.com/4503659/147930042-e0c41bf4-d004-4579-8e4d-c7f5a398d53e.gif)

**Comment by rmeissner** [comment]
Transaction are mapped incorrectly:

The [tx for nonce 1](https://rinkeby.etherscan.io/tx/0x16d07d59f18f9d6df3e698733d659648a4850299cd02167840632dec766e26ea#statechange) is mapped to nonce 4.

Everything else seems to be shifted by 1

**Comment by fmrsabino** [comment]
Issue has been fixed:

Staging: https://safe-client.staging.gnosisdev.com/v1/chains/4/safes/0x219a1a38FB8e57d9b2253b78f9fE1E27E595426c/transactions/history
Production: https://safe-client.gnosis.io/v1/chains/4/safes/0x219a1a38FB8e57d9b2253b78f9fE1E27E595426c/transactions/history
