### ISSUE TITLE
Add ABIs for Pangolin on Avalanche

### ISSUE THREAD

**Issue by prodesert22** [gnosis/safe-transaction-service#604]
I would like to request to add contract ABIs for Pangolin Dex which was recently added https://github.com/gnosis/safe-apps-list/issues/102
- Pangolin Token: [ABI](https://snowtrace.io/address/0x60781c2586d68229fde47564546784ab3faca982#code)
- Pangolin Router: [ABI](https://snowtrace.io/address/0xE54Ca86531e17Ef3616d22Ca28b0D458b6C89106#code)
- MiniChefV2: [ABI](https://snowtrace.io/address/0x1f806f7C8dED893fd3caE279191ad7Aa3798E928#code)
- StakingRewards: [ABI](https://snowtrace.io/address/0x78d4BFb3b50E5895932073DC5Eb4713eb532941B#code) (It is used by several Single Stake contracts)
- GovernorAlpha: [ABI](https://snowtrace.io/address/0xb0Ff2b1047d9E8d294c2eD798faE3fA817F43Ee1#code)

**Comment by Uxio0** [comment]
https://help.gnosis-safe.io/en/articles/4971390-submit-an-abi
