### ISSUE TITLE
Latest version - DB migration issue on PostgreSQL v10

### ISSUE THREAD

**Issue by air3ijai** [gnosis/safe-transaction-service#605]
**Describe the bug**
We just synced code  from the upstream repository and observed that one of the container failed to start and it is `worker`. We see the following error in the logs
> django.db.utils.OperationalError: cannot CREATE INDEX "history_erc20transfer" because it has pending trigger events

<img width="896" alt="Screenshot 2022-01-04 at 18 32 27" src="https://user-images.githubusercontent.com/88528265/148091820-bc18ad1c-2e4d-436c-a4aa-57d180db1e72.png">

Looks like some migration failed. The rest of the containers started successfully. When we roll back to the our precedent build from October of 2021 it started to work but we have some issue with the backend.

**To Reproduce**
1. Upgrade Transaction service components to the latest version
2. Run Transaction service on old DB PostgreSQL v10

**Expected behavior**
Transaction service components should do all required migrations without issue

**Environment**
 - Environment: Staging for now
 - Chain: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
1. Probably upgrade to the PostgreSQL v13 may solve the issue, but we need to solve this on Staging before moving to the Production.
2. If upgrade is required we probably should do is simultaneously for application and DB.
3. Config service working as expected on same DB server - PostgreSQL v10

How we should proceed in such a case?

We need to prepare Production upgrade plan and we have the following questions:

1. Is there a way to fix migration issue on the latest code with PostgreSQL v10?
2. Can we upgrade DB to the PostgreSQL v13 on the old code from October of 2021?

Thank you!

**Comment by rmeissner** [comment]
You should always use release to run your service, to avoid such issues. 

We are running PostgreSQL v12 and will upgrade to PostgreSQL v13 soon.

So upgrading to PostgreSQL v13 should work.

**Comment by air3ijai** [comment]
@rmeissner which [release](https://github.com/gnosis/safe-transaction-service/releases) do you use with your PostgreSQL v12?

**Comment by Uxio0** [comment]
> @rmeissner which [release](https://github.com/gnosis/safe-transaction-service/releases) do you use with your PostgreSQL v12?

Latest available
