### ISSUE TITLE
Hexdata not decoded on polygon

### ISSUE THREAD

**Issue by shredding** [gnosis/safe-transaction-service#606]
I'm opening a ticket as suggest [here](https://help.gnosis-safe.io/en/articles/4971390-submit-an-abi).

I have the same issue I had on this one https://github.com/gnosis/safe-transaction-service/issues/566.

But it's now not working on polygon.

E.g.:

https://polygonscan.com/address/0x96b2168F3E903158c2b154789EB97221e34d4cCa#readContract

I also wonder, if we use that factory to create a new token (like this one: https://polygonscan.com/address/0xA2c2b3e22C7548cF08D453930BF6139efC4Fdc0c), will it take time to pick it up for this new token or is it able to figure it out from the underlying proxy.

Is there a way to manually wire it?

**Comment by Uxio0** [comment]
Hi,

[Contract ABI was automatically added by our indexer](https://safe-transaction.polygon.gnosis.io/api/v1/contracts/0x96b2168F3E903158c2b154789EB97221e34d4cCa/) and [same for the token](https://safe-transaction.polygon.gnosis.io/api/v1/tokens/0xA2c2b3e22C7548cF08D453930BF6139efC4Fdc0c/)

Cheers

**Comment by shredding** [comment]
thx
