### ISSUE TITLE
Add "origin" to transaction 

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-transaction-service#61]
It is planned to allow Safe apps to submit transactions to the interface. As an owner of a Safe I would like to know from which service the transaction provided. For this we should add a "origin" field when sending the transaction meta to the service.

Notes:
- origin field is not part of the safe tx hash and therefore is not 100% trustworthy (maybe this should be mentioned in swagger) -> malicious owner could abuse this, but the advantages outweight this small risk
- origin field should be a `string`

**Comment by Uxio0** [comment]
@rmeissner I will set the maximum length of the field to 100 characters, is that ok?

**Comment by rmeissner** [comment]
In my opinion that should be sufficient

**Comment by nicosampler** [comment]
Hi @Uxio0 I just send a TX (POST) with the origin field:
![image](https://user-images.githubusercontent.com/4376509/74699667-0ebccd80-51e0-11ea-8154-999882063fc7.png)

and then, when I request the TX (GET) `https://safe-transaction.rinkeby.gnosis.io/api/v1/safes/0xEd99E368FCD7404045D1F20cb29274ecd9Ebf428/transactions/` the origin field for the nonce 76 is null.

any Idea what can be wrong? note that I'm on Rinkeby

**Comment by rmeissner** [comment]
If you post to staging dev env you also need to get from staging dev env (and not production)
