### ISSUE TITLE
Add simple authentication to transaction proposal

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-transaction-service#62]
Allow an owner to appoint delegate addresses that can propose transactions to the service without confirmations (perform a POST with transaction meta).

This would allow us to improve interaction with dapps by providing sdks or an chrome extension or mobile apps to propose transactions.

Notes:
- **ANY** owner should be able to add an delegate (backend should probably remember which owner did this) that is annotated with a label
- **ANY** owner should be able to remove **ANY** delegate
- **ANY** owner should be able to retrieve a list of all delegates and their label

**Comment by rmeissner** [comment]
* Check how to validate that a transaction was submitted by an owner

**Comment by rmeissner** [comment]
Currently you can use a hack around it by using a random transaction hash when submitting the transaction.

@rmeissner add more info on that

**Comment by Uxio0** [comment]
# API endpoints

## `POST /safes/{safe_address}/delegates`
```js
{
  "delegateAddress": "<checksummed-eth-address>",
  "label": "<short-string-max-50-chars>",
  "signature": "<hex-signature>"
}
```
### Generation of `<hex-signature>`
Multiple signature types are allowed:
- `Contract Signature` or `Approved Hash`. They must sign `keccak(checksummed-eth-address)`
- `EOA` or `eth_sign`.  The hash to sign must be `keccak(checksummed-eth-address + TOTP)`

### Calculation of [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm)
- TOTP will be used to prevent a repetition attack. E.g. a user signs a delegate, that delegate is compromised and removed but the signature is always valid, so another user could send that signature again to register the user as a delegate. This will prevent it.
- We will use a TOTP with `T0=0` and `Tx=3600` (1 hour)
- TOTP is calculated by taking the Unix epoch time (no milliseconds) and dividing by 3600 (natural division, no decimals)

## Example
- We want to add the owner `0x132512f995866CcE1b0092384A6118EDaF4508Ff`
- We calculate the TOTP. `Current epoch=1586779140`, so `1586779140 // 3600 = 440771`
- We sign `keccak("0x132512f995866CcE1b0092384A6118EDaF4508Ff440771")`

## `DELETE /safes/{safe_address}/delegates`
```js
{
  "delegateAddress": "<checksummed-eth-address>",
  "signature": "<hex-signature>"
}
```
Signature must be generated the same way that in `POST`

## `GET /safes/{safe_address}/delegates`
```js
{
  "delegateAddress": "<checksummed-eth-address>",
  "owner": "<checksummed-eth-address>", // Who added the delegate
  "label": "<short-string>",
  "signature": "<hex-signature>"
}
```
## Notes
- Every tx proposed must have a signature, so backend can check the sender. No signed txs must be discarded
-
