### ISSUE TITLE
500 error for getting balances

### ISSUE THREAD

**Issue by sche** [gnosis/safe-transaction-service#626]
**User support issue:**
https://discord.com/channels/907968493134155807/913377923308871680/927209590888759296

**Describe the bug**
500 error returned for the safe https://gnosis-safe.io/app/eth:0x921DCc4ba6872B4736eB1A22351E2a8Ce671C3E2/balances
![image](https://user-images.githubusercontent.com/2284385/147909895-b15af929-0d1b-42b2-9555-ebc4b0a484f9.png)

**Comment by fmrsabino** [comment]
The `/balances` endpoint was fixed: https://safe-transaction.mainnet.staging.gnosisdev.com/api/v1/safes/0x921DCc4ba6872B4736eB1A22351E2a8Ce671C3E2/balances/

However `/balances/usd` is returning `500` https://safe-transaction.mainnet.staging.gnosisdev.com/api/v1/safes/0x921DCc4ba6872B4736eB1A22351E2a8Ce671C3E2/balances/usd/

**Comment by fmrsabino** [comment]
It's working now: https://gnosis-safe.io/app/eth:0x921DCc4ba6872B4736eB1A22351E2a8Ce671C3E2/balances

Closing the issue.
