### ISSUE TITLE
Allow filtering transactions by modified

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe-transaction-service#63]
See https://github.com/gnosis/safe-react/issues/517 for details.

Create a new filter for `transactions/` endpoint to filter transactions modified after/before a timestamp:
  - `modified__lt`
  - `modified__gt`
  - `modified__gte`
  - `modified__lte`

It will allow [ISO 8601 datetimes](https://en.wikipedia.org/wiki/ISO_8601) like:
- `2020-02-27T10:46:15Z`
- `2020-02-27T10:46:15+00:00`
- `2020-02-27 10:46:15Z`

Backend needs to be adjusted to update `modified` on transactions when a new confirmation is added to the database.

**Comment by Uxio0** [comment]
@lukasschor @rmeissner I updated the issue with the implementation of the endpoint

**Comment by lukasschor** [comment]
Closing this as frontend seems to already have implemented this. Feel free to reopen if there is some work outstanding on your side.
