### ISSUE TITLE
Add ABI for AdminContract

### ISSUE THREAD

**Issue by nkitlabs** [gnosis/safe-transaction-service#631]
Please decode all methods of the following contract on Avalanche.

https://snowtrace.io/address/0x628811Cf4FA3Ea35f691909e0504735855A9F665#code

Thanks

**Comment by Uxio0** [comment]
https://help.gnosis-safe.io/en/articles/4971390-submit-an-abi

**Comment by nkitlabs** [comment]
great to here that, thanks :)
