### ISSUE TITLE
Add ABI for MockAlloc and MockRewardRate on rinkeby

### ISSUE THREAD

**Issue by nkitlabs** [gnosis/safe-transaction-service#632]
Hi , could you help decode ABI of following contracts on rinkeby?

https://rinkeby.etherscan.io/address/0x6f7ad059abaf4cf48fed85c1f4a24341d4014ced#code

https://rinkeby.etherscan.io/address/0xce4449c0b46a8cb7af895aee9a62fd3e4b69ab57#code

Thanks

**Comment by Uxio0** [comment]
https://help.gnosis-safe.io/en/articles/4971390-submit-an-abi
