### ISSUE TITLE
Backend returns same transaction separately

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-transaction-service#64]
Paul reported via Telegram that their Safe (https://gnosis-safe.io/safes/0x71B94163b085cc2ea7432D8cC96A94989Da4FD6e/transactions) shows the tx with nonce 18 as pending even though Etherscan shows it as successful.

https://safe-transaction.gnosis.io/api/v1/safes/0x71B94163b085cc2ea7432D8cC96A94989Da4FD6e%2F/transactions/ returns it twice:
- Once with 1 confirmation and pending
- Once with 2 confirmation and successful.

Why is that? Why isn't the backend able to connect both txs?
That might confuse the frontend.

**Comment by rmeissner** [comment]
but the 2 transactions with nonce 18 are different transactions ... ofcourse we return 2 of them

**Comment by pcowgill** [comment]
So then it’s more of a front end issue that I shouldn’t have had two tx with the same nonce in the first place? Or is the problem with MetaMask?

**Comment by Uxio0** [comment]
@pcowgill It was a mixed issue, backend was lacking a tx and frontend was not showing it right. Thank you for your reports Paul.
