### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by InoMurko** [gnosis/safe-transaction-service#640]
**Describe the bug**
CSRF disabled: https://github.com/gnosis/safe-transaction-service/commit/8e2591d84fb98329c04cc95aa9e2e7a28265e59c
https://docs.djangoproject.com/en/4.0/ref/csrf/

Is having CSRF disabled ok? 
I see it's not disabled in https://github.com/gnosis/safe-config-service/blob/d83b03a878adf03636329604c9e400cbb405b3e1/src/config/settings.py#L70

Cheers

**Comment by Uxio0** [comment]
Hi @InoMurko , it's not very relevant as we have a REST API with no authentication, but it can be important for the `admin` page. Thanks for noticing, I will fix it
