### ISSUE TITLE
Data hasn't been decoded even ABI is uploaded on Etherscan

### ISSUE THREAD

**Issue by nkitlabs** [gnosis/safe-transaction-service#648]
Hi team, 

regarding the issue #632 , it seems that the data haven't been decoded. Could you please help check whether your backend is updated? 

I tried decoding using url https://safe-transaction.rinkeby.gnosis.io/ with signature 0x20b87853 but I got 404 Not Found.

**Comment by nkitlabs** [comment]
I did verify the contracts. 

https://rinkeby.etherscan.io/address/0x6f7ad059abaf4cf48fed85c1f4a24341d4014ced#code
https://rinkeby.etherscan.io/address/0xce4449c0b46a8cb7af895aee9a62fd3e4b69ab57#code

or is the abi specific per address? (if i call another contract whose has the same interface, it will not be decoded)

**Comment by Uxio0** [comment]
Did you do this?

> If you create a Safe transaction calling an unknown contract (even if not executed), and the contract is present on Sourcify/Etherscan (or equivalent on the network), it will be automatically added to the Gnosis Safe transaction service within 1 hour.

So you would have to create txs calling `0xce4449c0b46a8cb7af895aee9a62fd3e4b69ab57` and `0x6f7ad059abaf4cf48fed85c1f4a24341d4014ced`

**Comment by nkitlabs** [comment]
I created a tx and wait for an hour but still not decoded (query via https://safe-transaction.rinkeby.gnosis.io/), please help check.

https://rinkeby.etherscan.io/tx/0xc56b708b9a7ac9685d49ec22ea50e54208f51fd1717ea2a06b4356de30fd17e1

**Comment by Uxio0** [comment]
You need to create a Safe transaction from our interface, not a regular ethereum transaction. We don't index all the blockchain 😉

**Comment by Uxio0** [comment]
This time I added the ABIs manually, for next ones you need to follow https://help.gnosis-safe.io/en/articles/4971390-submit-an-abi and create a Safe transaction 😉

**Comment by nkitlabs** [comment]
I got your point, btw thanks for helping us.

**Comment by Uxio0** [comment]
No worries 👍🏻
