### ISSUE TITLE
Safe creation transaction details

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe-transaction-service#65]
We want to display additional information about the Safe creation transaction:
- Creation date/time
- Tx hash of Safe creation transaction
- Initiator of Safe creation

We need an endpoint that provides this information for a given Safe address

Related to https://github.com/gnosis/safe-react/issues/554

**Comment by rmeissner** [comment]
This can be a separate endpoint for now

**Comment by Uxio0** [comment]
#Endpoint proposal

## URL 
GET /api/v1/safes/<address>/creation/

## Response
```
created: "<iso 8601 datetime>",
transactionHash: "<keccak-hash>",
creator: "<checksummed-address>"
```
