### ISSUE TITLE
API displays at most 10 owners

### ISSUE THREAD

**Issue by bh2smith** [gnosis/safe-transaction-service#66]
The following safe owns 20 safes, but only the first 10 appear here

https://safe-transaction.gnosis.io/api/v1/owners/0x583788f490a278DB2a8d6D7226264b4985f75678/

**Comment by tschubotz** [comment]
It now displays 19 for me @bh2smith . Maybe there's just a delay :)

**Comment by Uxio0** [comment]
For me it's 20 now @bh2smith

**Comment by Uxio0** [comment]
> The following safe owns 20 safes, but only the first 10 appear here
> 
> https://safe-transaction.gnosis.io/api/v1/owners/0x583788f490a278DB2a8d6D7226264b4985f75678/

Some of them were created a couple of minutes before you opened the issue 😬 It's expected that the service has some delay, it should be 30 seconds at most but depending on nodes, reorgs, etc could be a couple of minutes

**Comment by bh2smith** [comment]
In this case it was a couple of minutes. Like 5. Very happy to see there’s no problem!
