### ISSUE TITLE
Gnosis Documentation Out of Date

### ISSUE THREAD

**Issue by Anteloper** [gnosis/safe-transaction-service#666]
**Describe the bug**
[Safe Transaction Service documentation](https://docs.gnosis-safe.io/tutorials/tutorial_tx_service_initiate_sign) is out of date

**To Reproduce**
The following is broken:
- Running the provided [example code](https://gist.github.com/rmeissner/0fa5719dc6b306ba84ee34bebddc860b) for proposing a transaction returns a 422 due to incorrect contract hash. I assume EIP-712 validation has changed.
- The [link to how EIP-712 structuring happens](https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafe.sol#L403) on the safe side is broken
- Not as urgent for my particular needs but worth noting this applies to the SDK documentation too. The import structure has a breaking change that is not reflected in the documentation. Which says 
```
import { EthersAdapter } from '@gnosis.pm/safe-core-sdk'
```
But that structure is no longer correct

**Expected behavior**
Documentation should provide working examples and up-to-date usage guidelines. A documentation for proposing a batch of multiple tx's to the safe contract would be highly appreciated as well

**Comment by germartinez** [comment]
Hi @Anteloper, regarding the SDK documentation are you refering to https://docs.gnosis-safe.io/ or anywhere in the repo? In case you are referring to the docs in the website, it's a known issue that will be soon updated. The repos should be updated.
Thank you!

**Comment by Anteloper** [comment]
I'm referring to the docs on the website, but I submitted this issue here because I believe there has been a behavior change either in this repo or in the safe repo. I'm not sure if that change is intended or not, but I can be reasonably sure it happened because the [example implementation](https://gist.github.com/rmeissner/0fa5719dc6b306ba84ee34bebddc860b) (which the docs link to) doesn't work

There is currently no accurate documentation for how to submit proposed transactions to gnosis anywhere on the internet as far as I can tell. Is it possible to prioritize the documentation update?

**Comment by germartinez** [comment]
@Anteloper you may want to check this one: https://github.com/gnosis/safe-core-sdk/blob/main/packages/guides/integrating-the-safe-core-sdk.md
It shows how to use the [Safe Core SDK](https://github.com/gnosis/safe-core-sdk/tree/main/packages/safe-core-sdk) to create and sign a Safe transaction and propose it to the [Safe Transaction Service](https://github.com/gnosis/safe-transaction-service) using the [Safe Service Client](https://github.com/gnosis/safe-core-sdk/tree/main/packages/safe-service-client).

**Comment by Anteloper** [comment]
Excellent will try that thank you

**Comment by Anteloper** [comment]
Thank you this is great. One other question - can you point me to documentation on proposing a transaction for a token other than ETH on a safe?
