### ISSUE TITLE
500 when using date filter on incoming transactions

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-transaction-service#67]
Example: https://safe-transaction.gnosis.io//api/v1/safes/0x71B94163b085cc2ea7432D8cC96A94989Da4FD6e/incoming-transactions/?limit=2&execution_date__lte=2020-02-20%2019:35:06

**Comment by Uxio0** [comment]
The error is awesome `Unsupported lookup 'lte' for DateTimeField, perhaps you meant lte or lt or gte`

**Comment by rmeissner** [comment]
Try lte xD

**Comment by Uxio0** [comment]
It's fixed now on staging/dev environments, thanks for the report
