### ISSUE TITLE
Data wasn't decoded even contract verified in snowtract (Avalanche)

### ISSUE THREAD

**Issue by tapakornl** [gnosis/safe-transaction-service#672]
I know that I need to open the issue to submit ABI, but I think maybe you guys wanna get the cases where the ABI isn't automatically decoded.

- gnosis address: ```0x2ABC32Fcf8584Aba161b33133af55cD3f94Ba288```
-safe tx hashes: ```0x3ac1ea4eccff000c7e5e9c09cbc2b346c841bdd0d486d1e051800e232f1e3ed9```, ```0xb15f65f548cad848a535f8e33412cba2a47cf8047634be5ab5cdfcbc66f0e5db```
- contract that interacted to: ```0x628811Cf4FA3Ea35f691909e0504735855A9F665 ```

**Comment by Uxio0** [comment]
Hi, it was a caching issue and it's fixed now
