### ISSUE TITLE
Can't send etag header within GET requests due to CORS

### ISSUE THREAD

**Issue by Agupane** [gnosis/safe-transaction-service#79]
If I try to send a get request to fetch the transactions list, I got an CORS error because Access-Control-Allow-Headers is missing in preflight response.

I think it should be fixed just adding on the response headers
`Access-Control-Allow-Headers`

**Comment by Uxio0** [comment]
Hi @Agupane, I added this to the response headers, it should be fixed now:

```
Access-Control-Allow-Headesr: if-match, if-modified-since, if-none-match
```

**Comment by Agupane** [comment]
It's working now, feel free to close this issue :)

**Comment by Uxio0** [comment]
Deployed now to every environment including production
