### ISSUE TITLE
Add flag to hide transactions without confirmations

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-transaction-service#83]
To prevent spamming of the interface we should make it possible that the backend returns only transactions that have at least 1 confirmation.

Proposed flag name: `hasConfirmations`

The flag should be added to the current `transactions` endpoint

Notes for future:
- this should become the default behaviour. 
- transactions submitted by a delegate should be an exception.

**Comment by Uxio0** [comment]
> transactions submitted by a delegate should be an exception.

**Comment by rmeissner** [comment]
Yes, I didn't mention the owner because I assumed the owner would just add a confirmation signature for the transaction and then it would be a transaction with at least 1 confirmation. but yes we can also allow that owners can submit a transaction without a confirmation by providing a different signature :)

**Comment by Uxio0** [comment]
I think that would be a little messy, I was meaning txs with already one confirmation (offchain). If an owner proposes a signature it must have already a confirmation, if they don't want to provide a confirmation (I think that doesn't make too much sense) they should use a delegate
