### ISSUE TITLE
Token DTO to include the logo image URL

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-transaction-service#86]
Currently the Token DTO does not contain the URL to the logo image which most of the time resolves the formula `<S3 server>+<token address>.png`, however if that fails the URL must be resolved against the relay service.

To prevent multiple requests in clients and to mimic the structure of the DTO in the relay service, it would be nice to include it in the object returned by the transaction service too.

**Comment by Uxio0** [comment]
This is already implemented on staging
