### ISSUE TITLE
Decode Multisend

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe-transaction-service#94]
# What is needed?
Decode Multisend transaction in the backend and link a parent transaction with the child transactions

# Background
- Currently we only show the "parent" Multisend transaction in the transaction list.
- With Safe Apps we expect more Multisend transactions being used.
- We should show what sub-transactions are part of this Multisend transaction in the expanded transaction details

# Considerations
- Should we decode multi-level Multisends as well? (= Multisend tx that include one or more Multisend txs, etc.)

# Related issues
Frontend ticket in safe-react: https://github.com/gnosis/safe-react/issues/865

# Endpoint
tbd

## URL 
tbd

## Response
tbd

**Comment by Uxio0** [comment]
Implemented by e511032ff98b9666d851ebd0c53854fc0eeff3e9
