### ISSUE TITLE
Decode smart contract interactions

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe-transaction-service#95]
# What is needed?
We should return `dataDecoded` for most contract interactions

# Background
With Safe Apps we try to get to a point where the user only needs to trust the information provided by the interface and not rely on the information provided by the safe app. As most Safe App interactions are assumed to be contract interactions, we need a scalable way to decode these interactions and provide this information to the user in the following places in the interface:
- In the review screen when the user initiates a new Safe App interaction
- In the transaction list when users confirm Safe App interactions in the queue or revisit past interactions in the history

# Related issues

Decode in the transaction list: https://github.com/gnosis/safe-react/issues/882
Decode in the transaction review screen: https://github.com/gnosis/safe-react/issues/898

# Endpoint
Endpoint already exists for the transaction list. We might need a new endpoint to decode the transaction data for the Safe App transaction review screen.

## URL 
/safes/{address}/transactions/

## Response
tbd

**Comment by Uxio0** [comment]
I would need more background for this ticket. What contracts need to be supported?

**Comment by Uxio0** [comment]
Related issue could be #103

**Comment by Uxio0** [comment]
Look also at the metadata for the new 0.6.0 contracts

**Comment by Uxio0** [comment]
Add support for testing contracts (environment linked) like https://rinkeby.etherscan.io/address/0x2d4A49a1bc366D1750501F0976c4736A5192e687#code

**Comment by Uxio0** [comment]
@tschubotz commented:

Background: 
So far we have a limited number of contracts that we decode.
I've pulled a list of the most popular contracts by number of calls from Safes. I checked the top 100. 
https://explore.duneanalytics.com/queries/11954/source

Task/ask:
Please decode data with the ABIs of the contracts in this gist: https://gist.github.com/tschubotz/099371a18b4b6357d4bd02d9912a0cdf

**Comment by tschubotz** [comment]
There is also this repo with function/event signatures: https://github.com/ethereum-lists/4bytes
